### ISSUE TITLE
Allow access to the close code and reason

### ISSUE THREAD

**Issue by nox** [snapview/tungstenite-rs#10]
When a WebSocket connection is closed by the server side, how does a user retrieve the close code and reason?

**Comment by nox** [comment]
Seems like there is a similar issue on the client side, where we can't specify any particular code and reason.

**Comment by application-developer-DA** [comment]
Right. It is simple to implement ([when creating close frame,](https://docs.rs/tungstenite/0.1.1/tungstenite/protocol/frame/struct.Frame.html#method.close) you can specify that), but currently this particular part is not exposed to the user.

Seems reasonable to allow a user to get an access to such internals (we did not use those things in our project, that was the reason why they were not added to the "public interface", but yeah, indeed it may be useful for those ones who are dealing with WebSocket internals).

**Comment by nox** [comment]
Yeah for my use case I think having access to frames would be better, and then I could handle them however I want.

**Comment by agalakhov** [comment]
Fixed in the devel branch. Now the close() function takes an optional reason, and the ConnectionClosed error also includes one.
