### ISSUE TITLE
Echo server in README.md panics :(

### ISSUE THREAD

**Issue by iago-lito** [snapview/tungstenite-rs#100]
I'm trying to play around with the very first snippet provided in this `tungstenite` repo:

```rust
use std::net::TcpListener;
use std::thread::spawn;
use tungstenite::server::accept;

fn main() {
    let server = TcpListener::bind("127.0.0.1:9001").unwrap();
    for stream in server.incoming() {
        spawn(move || {
            let mut websocket = accept(stream.unwrap()).unwrap();
            loop {
                let msg = websocket.read_message().unwrap();
                if msg.is_binary() || msg.is_text() {
                    websocket.write_message(msg).unwrap();
                }
            }
        });
    }
} 
```

After I `cargo run`, the program hangs so I suspect it runs correctly. And from another terminal:

    $ echo hey! | nc 127.0.0.1 9001

But the command fails (errcode 127) and the server panicks:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: HandshakeError::Failure(Protocol("invalid token"))', src/libcore/result.rs:1165:5
```

I am not sure what I am missing here. Is this the expected way to connect to a `tungstenite` websocket server?

**Comment by agalakhov** [comment]
`nc` does plain TCP connections, not WebSocket ones. Please use proper WebSocket client.

**Comment by rofrol** [comment]
This worked for me:

`cargo run --example server`

1. Open web browser dev console.
2. Use ws and not secure wss, otherwise I get 'invalid token`.
3. No custom protocol.
4. Run this:

```javascript
var exampleSocket = new WebSocket("ws://www.example.com/socketserver");
exampleSocket.send("Here's some text that the server is urgently awaiting!"); 
```

5. Success! Server displayed message.

- https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications
- https://appdividend.com/2019/04/03/websockets-tutorial-with-example-getting-started-with-websockets/

**Comment by jadedevin13** [comment]
Can this be reopened?

I'm getting this error.
![image](https://user-images.githubusercontent.com/6671182/74263825-84392180-4d3a-11ea-9b30-83965d56f0c1.png)

**Comment by najamelan** [comment]
@jadedevin13 please, nor the complete code nor the error message are shown in the screenshot. I doubt anyone can help you based on that.

**Comment by jadedevin13** [comment]
Here's the sample code.

```js
var exampleSocket = new WebSocket("ws://www.example.com/socketserver", "sip");
```

**Comment by jadedevin13** [comment]
I just submitted a new issue since it's not related to a tcp issue.

https://github.com/snapview/tungstenite-rs/issues/107

**Comment by brandonros** [comment]
I get the same problem.

Server:

```rust
extern crate tungstenite;

fn main() {
    let server = std::net::TcpListener::bind("127.0.0.1:9001").unwrap();
    for stream in server.incoming() {
        std::thread::spawn (move || {
            let mut websocket = tungstenite::server::accept(stream.unwrap()).unwrap();
            loop {
                let msg = websocket.read_message().unwrap();
                println!("{:?}", msg);
            }
        });
    }
}
```

Client side JavaScript (in Chrome):

```
const run = async () => {
  const socket = new WebSocket('ws://localhost:9001')
  await new Promise(resolve => socket.onopen = resolve)
  socket.send(new Uint8Array[
    0x00,
    0x00,
    0x07,
    0xE5,
    0x02,
    0x10,
    0x03,
    0x55,
    0x55,
    0x55,
    0x55
  ])
}

run()
```

```
$ cargo build
   Compiling can-utils-rs v0.0.1 (/Users/bros/Desktop/can-utils-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.82s
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: HandshakeError::Failure(Protocol("invalid token"))', src/main.rs:7:33
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: HandshakeError::Failure(Protocol("invalid token"))', src/main.rs:7:33
```
