### ISSUE TITLE
crates.io has incorrect http dependency

### ISSUE THREAD

**Issue by svenlarson** [snapview/tungstenite-rs#101]
I'm new to rust but I think this is a problem:

The dependencies on https://crates.io/crates/tungstenite are `http ^0.1.19`, but the Cargo.toml on github has http at `0.2.0`. This causes the example not being able to build when using the tungstenite crate.

**Comment by application-developer-DA** [comment]
I was not able to reproduce the issue (client and server examples from master compile without any issues on my machine). The dependency on crates.io seems to be correct, the master branch uses a newer version of `http`. Have you tried to execute `cargo update`? I assume something has previously been used with different dependencies and caused some compile time errors on your side (or maybe you're using a wrong branch).
