### ISSUE TITLE
How can I pass websocket to thread?

### ISSUE THREAD

**Issue by tomocrafter** [snapview/tungstenite-rs#102]
```Rust
for stream in listener.incoming() {
    let msg = websocket.read_message().unwrap();
    if msg.is_text() {
        let msg = match msg.to_text() {
            Err(_) => {
                websocket.close(None);
                break;
            }
            Ok(msg) => msg,
        }
        spawn(move || { // <- Move of 'websocket' occurs here!
            calculate(|progress| {
                websocket // <- Used here.
                    .write_message(Message::Text(progress.to_string()))
                    .unwrap();
            });
        });
    }
});
```
It causes this following error:
![image](https://user-images.githubusercontent.com/10905364/71326448-4a1f8080-253e-11ea-8d99-1bb47eeb4598.png)

Should I use tokio-tungstenite? currently, I am trying to use tokio-tungstenite but seems like it is no longer maintained.

**Comment by application-developer-DA** [comment]
Hm, based on the `listener.incoming()`, I may assume you're writing some sort of server, but the code inside the `for` loop does not make any sense to me as I would expect `stream` to be used to create a `WebSocket` connection, but the example uses some different `websocket` which apparently was defined before. If you try to move it like that, then it won't work of course, but I'm not sure what are you trying to accomplish with that.

What I think you may have wanted is to process each incoming connection in a separate thread, please take a look at one of our examples: https://github.com/snapview/tungstenite-rs/blob/master/examples/server.rs

> Should I use tokio-tungstenite? currently, I am trying to use tokio-tungstenite but seems like it is no longer maintained.

`tokio-tungstenite` is definitely a way to go, most of our users actually use `tokio-tungstenite` and the only reason `tungstenite-rs` has so many downloads is that it's used as dependency in a big amount of projects, including the "not yet merged" async version of `tokio-tungstenite`.

`tokio-tungstenite` is maintainced, it's just does not yet have the async version merged into master, but thanks to our amazing community it has already been ported to new futures/tokio and will soon be merged into `master` and published on crates.io
