### ISSUE TITLE
Remove ErrorTrait::description implementation

### ISSUE THREAD

**Issue by najamelan** [snapview/tungstenite-rs#111]
`description` is deprecated and now throws warnings when building. I didn't file a PR because the recommended solution here is to use a `Display` impl, but `tungstenite::Error` already has a display impl, only the text returned by it is not the same as from the `ErrorTrait` impl, so some decision needs to be made.

Adding `export RUSTFLAGS="-D warnings"` to ci builds can help catch this automatically.

**Comment by application-developer-DA** [comment]
Ok. Does not seem like anyone really uses the `description()`, so probably removing it won't harm.
