### ISSUE TITLE
Connection closing

### ISSUE THREAD

**Issue by serzhiio** [snapview/tungstenite-rs#114]
If i send Message::Close(None) to server will i have guarantee of connection drop even if channel is hanging?

**Comment by application-developer-DA** [comment]
What do you mean by "channel is hanging"?

`WebSocket` cannot drop itself. After accepting a close message on a server side, it will return an `Err` with the corresponding code, upon reception of which you the `WebSocket` is normally dropped (as well as the underlying stream which is owned by it).

In case of `tokio-tungstenite` it happens "automatically" in a way that a `Stream` eventually returns `None` and the object is dropped.

**Comment by serzhiio** [comment]
By hanging i mean that connection is not dropped but server does not
respond.

чт, 16 апр. 2020 г., 01:29 Daniel Abramov <notifications@github.com>:

**Comment by application-developer-DA** [comment]
In WebSockets the connection close is normally initiated by a server, not by a client. The server responds always as long as it is required according to the RFC. The connection on both server and client is not dropped "automatically" (and it should not be), but you get an `Err::ConnectionClosed` once "it's safe" to drop the object.

You can of course drop it right after sending `Close` to server, but in this case you may observe some errors in the logs of your server ("peer connection reset without closing handshake", "broken pipe" or something similar).

**Comment by serzhiio** [comment]
thx for helping me
