### ISSUE TITLE
Passing vendored feature to native-tls

### ISSUE THREAD

**Issue by TJRoh01** [snapview/tungstenite-rs#118]
It is sometimes necessary to statically link OpenSSL when compiling which is achieved by activating the "venodred" feature in the openssl crate. For this reason native-tls, that you use as a dependency, also has this feature that it simply passes to openssl when compiling. 

I would really appreciate it if you could add similar functionality in tungstenite.

**Comment by application-developer-DA** [comment]
Seems to be solved now.
