### ISSUE TITLE
server cleanup example, non blocking??

### ISSUE THREAD

**Issue by x37v** [snapview/tungstenite-rs#120]
I'm writing a library that starts a websocket spawning service and I want to be able to kill it when I drop the reference to the service.

My thought is that I can either have some shared boolean or a channel with a command that can the thread that spawns websockets can check to see if it should exit but I can't figure out how to loop in such a way that I can check this exit condition without having an incoming connection trigger a loop iteration.

The examples I've seen use `incoming` which says:

> The returned iterator will never return None and will also not yield the peer's SocketAddr structure. Iterating over it is equivalent to calling accept in a loop.

My guess is that I need to use `accept` but also `set_nonblocking` but when I set that, the client I'm attaching gets an error: 

`Io(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" })`

Am I missing some sort of setup? Is there an alternative approach I should take?

Here is a paired down server that I'm using for testing:
```rust
use std::io::ErrorKind;
use std::net::{SocketAddr, TcpListener};
use std::str::FromStr;
use std::thread::spawn;
use tungstenite::accept;

fn main() {
    let server =
        TcpListener::bind(SocketAddr::from_str("127.0.0.1:3002").unwrap()).expect("couldn't bind");
    server
        .set_nonblocking(true)
        .expect("cannot set to non blocking");

    let handle = spawn(move || loop {
        let stream = server.accept();
        let (stream, _addr) = match stream {
            Ok(s) => s,
            Err(e) => match e.kind() {
                ErrorKind::WouldBlock | ErrorKind::TimedOut => continue,
                e @ _ => {
                    println!("tcp accept error {:?}", e);
                    return;
                }
            },
        };

        println!("spawn websocket");
        spawn(move || {
            if let Ok(mut websocket) = accept(stream) {
                loop {
                    if let Ok(msg) = websocket.read_message() {
                        println!("{:?}", msg);
                    }
                }
            }
        });
    });
    let _ = handle.join();
}

```

and a basic client, based off the examples here

```rust
use tungstenite::{connect, Message};
use url::Url;

fn main() {
    let (mut socket, response) =
        connect(Url::parse("ws://localhost:3002/socket").unwrap()).expect("Can't connect");

    println!("Connected to the server");
    println!("Response HTTP code: {}", response.status());
    println!("Response contains the following headers:");

    for (ref header, _value) in response.headers() {
        println!("* {}", header);
    }

    socket
        .write_message(Message::Text(
            "{\"COMMAND\":\"IGNORE\",\"DATA\":\"/foo/bar\"}".into(),
        ))
        .unwrap();
    socket.close(None);
}
```

**Comment by x37v** [comment]
btw, the error i get is from the accept call `HandshakeError::Interrupted(...)`

**Comment by agalakhov** [comment]
`Interrupted` means that you have to continue your handshake. It corresponds to `WouldBlock`. If you get this error, you should check if you have anything else to do, and then continue with `MidHandshake` you just got.

**Comment by application-developer-DA** [comment]
> Am I missing some sort of setup? Is there an alternative approach I should take?

I might be wrong, but it seems like you're trying to invent some sort of [tokio runtime](https://tokio.rs/) here :) Perhaps using our [async-version](https://github.com/snapview/tokio-tungstenite) of a library would do a better job (also it has an advantage that it scales much better and you don't need to invent all those abstractions to synchronize things).

> I'm writing a library that starts a websocket spawning service and I want to be able to kill it when I drop the reference to the service.

That seems to be easily doable with Tokio, but you would need to get familiar with Tokio in order to use it right. You could for sure emulate the whole thing using `std` and threads, but I doubt it would be a better solution than using Tokio in this case (especially if we're talking about real-world production usage).

**Comment by x37v** [comment]
> > Am I missing some sort of setup? Is there an alternative approach I should take?
> 
> I might be wrong, but it seems like you're trying to invent some sort of [tokio runtime](https://tokio.rs/) here :) Perhaps using our [async-version](https://github.com/snapview/tokio-tungstenite) of a library would do a better job (also it has an advantage that it scales much better and you don't need to invent all those abstractions to synchronize things).
> 
> > I'm writing a library that starts a websocket spawning service and I want to be able to kill it when I drop the reference to the service.
> 
> That seems to be easily doable with Tokio, but you would need to get familiar with Tokio in order to use it right. You could for sure emulate the whole thing using `std` and threads, but I doubt it would be a better solution than using Tokio in this case (especially if we're talking about real-world production usage).

@application-developer-DA yeah, maybe you're right, though I feel like I'm 99% of the way without the extra infrastructure.

One of the additional problems I'm trying to solve here is that I want to read from a channel and have all the active websockets operate on the same data from that channel. That is quite easy to manage in a single sync thread I can have non blocking `accept` (ideally `read_message` as well).

1. check for new connections to accept, accept and add to list
2. read from channel into vector
3. for all websockets (with that vector)
    1. write out any appropriate messages based on the channel data above.
    2. see if there are any incoming messages, respond to them, potentially writing (pong), potentially exiting.
4. cleanup any websockets that exited (remove them from vector.
5. loop back to 1.

looked a bit at both [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite) and [async-tungstenite](https://github.com/sdroege/async-tungstenite) and.. well, maybe i should just ask some questions there.. the main issue being maybe just my understanding, but I couldn't see a way to do read with a timeout that won't ever drop messages? Also, the broadcast (shared commands) shouldn't be too hard but actually adds quite a bit more complexity.

**Comment by x37v** [comment]
okay, i think i've figured out an approach with async tasks, it complicates things and adds a number of mutexes, but I'm guessing it'll be beneficial in the long run.

**Comment by agalakhov** [comment]
Better don't use mutexes within async tasks unless you know what you're doing. You should not do anything blocking within async. In most cases what you want to do is doable with better performance using MPSC.

**Comment by application-developer-DA** [comment]
Ok, I'm going to close this issue, it seems to me that it was sorted out. But actually using `tungstenite-rs` in a non-blocking way only makes sense if you either design some sort of your own tokio or if you're using `tungstenite-rs` in your own wrapper like `async-tungstenite` or `warp`. For the rest of the usages I think it makes sense to use `tokio-tungstenite`, since in **real-world scenarios** you would also like to have some interoperability with other network related libraries and currently the ecosystem of Rust crates relies on futures and tokio in that regard.
