### ISSUE TITLE
Sending image example

### ISSUE THREAD

**Issue by hyousef-rusty** [snapview/tungstenite-rs#121]
Can you provide a simple example that keep sending an image to a browser.
In my Rust OpenCV function, I keep overriding the picture in the service every time a new frame is captured, I need to push it directly to the browser, the idea came to my mind is using websocket instead of normal JavaScript function with Friday timer.

Thanks

**Comment by agalakhov** [comment]
There is nothing special about sending images. They are just binary WebSocket messages, `Vec<u8>`. The image format is up to you.

**Comment by application-developer-DA** [comment]
@agalakhov is right. Just use the regular [write_message](https://docs.rs/tungstenite/0.10.1/tungstenite/protocol/struct.WebSocket.html#method.write_message) function and create [a binary message](https://docs.rs/tungstenite/0.10.1/tungstenite/enum.Message.html#variant.Binary) our of your picture, that would do the job.
