### ISSUE TITLE
Working with wss

### ISSUE THREAD

**Issue by hyousef-rusty** [snapview/tungstenite-rs#123]
Once I open the client as `wss` the server git panicked with error: `HandshakeError::Failure(Protocol("invalid token"))`

**Comment by agalakhov** [comment]
This happens if you try to connect i.e. with WSS to a WS-only server.

**Comment by hyousef-rusty** [comment]
So, hire to define the server as `wss`

**Comment by agalakhov** [comment]
You can't just "define" it. You have to provide server certificate and to perform TLS handshake using i.e. `rustls` or `native-tls`. What you get from the TLS library after performing the handshake is the stream to be passed to Tungstenite.
