### ISSUE TITLE
Max size of receive queue?

### ISSUE THREAD

**Issue by kehlert** [snapview/tungstenite-rs#129]
I found the information about the max size of the send queue here:
https://docs.rs/tungstenite/0.11.0/tungstenite/protocol/struct.WebSocketConfig.html

I'm wondering is there's a max size to the receive queue? While I'm not certain, it seems that the websocket is dropping messages. I'd like to use an unlimited receive queue.

**Comment by application-developer-DA** [comment]
We never silently drop messages (that would be a bug). We're using https://docs.rs/input_buffer/0.3.1/input_buffer/ on the receiving end (also written by us, by @agalakhov to be more precise).

I don't think [you'll hit the limit](https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/frame/mod.rs#L161) of the queue in any practical application though :)
