### ISSUE TITLE
cannot borrow data in an `Arc` as mutable.

### ISSUE THREAD

**Issue by ZoroSC** [snapview/tungstenite-rs#131]
When storing the websocket connection in an arc. I'm unable to later reference it for later use, as I get an error

See the error: https://i.imgur.com/Y6v3AJJ.png 

I'm unsure if this my fault or something else as I'm fairly new to rust whole concept of rust. 

The struct where im storing the connection: 
```rust
pub gateway_connection: Option<Arc<tungstenite::WebSocket<tungstenite::client::AutoStream>>>
```

Where im trying to use it: 
```rust
		let socket = initclient.unwrap().gateway_connection.unwrap();
		let msg = socket.read_message().expect("Error reading message from gateway.").to_text().unwrap().to_owned();
```

**Comment by agalakhov** [comment]
You use `Arc` incorrectly. Since it can be accessed from many threads, you have to think about thread safety and introduce some locking mechanisms too.
