### ISSUE TITLE
Build timeout due ERROR: context deadline exceeded

### ISSUE THREAD

**Issue by steelx** [snapview/tungstenite-rs#136]
Build's ok on local machine. But when doing same on GCP, build timeout.
I increased the timeout to 900seconds (15mins) GCP allows this as maximum.
Also increased RAM to 1GB.

Still I'm having same issue. (complete log [here](https://pastebin.run/cwBsSQKKqq))

**tungstenite**

> TIMEOUT
> ERROR: context deadline exceeded
```
Step #0 - "Build": [0m[91m [0m[91m [0m[91m [0m[91mCompiling[0m[91m [0m[91mtokio[0m[91m v[0m[91m0.2.22[0m[91m
Step #0 - "Build": [0m[91m [0m[91m [0m[91m [0m[91mCompiling[0m[91m [0m[91mtungstenite[0m[91m v[0m[91m0.10.1[0m[91m
TIMEOUT
ERROR: context deadline exceeded
Step #0 - "Build": [0m[91m [0m[91m [0m[91m [0m[91mCompiling[0m[91m [0m[91mfutures-util[0m[91m v[0m[91m0.3.5[0m[91m
```

**Comment by application-developer-DA** [comment]
I'm not sure that this error has something to do with tungstenite's source code. I've checked a couple similar issues in GitHub and StackOverflow and it seems like in most (or all?) cases it's related to the configuration.

**Comment by steelx** [comment]
> 
> 
> I'm not sure that this error has something to do with tungstenite's source code. I've checked a couple similar issues in GitHub and StackOverflow and it seems like in most (or all?) cases it's related to the configuration.

this is interesting both parties blaming each other -> https://github.com/flutter/flutter/issues/64931

**Comment by application-developer-DA** [comment]
@steelx , just wanted to ask if you were able to solve the issue and it it was related to rust / tungstenite?

**Comment by steelx** [comment]
> @steelx , just wanted to ask if you were able to solve the issue and it it was related to rust / tungstenite?

Hi. I was not able to compile. So I compiled locally and hosted on local machine.

**Comment by application-developer-DA** [comment]
Hm, ok, should we close the issue then? I'm just not sure if anyone would be able to investigate provided we don't have too much information about it.

**Comment by application-developer-DA** [comment]
I'm going to close it due to the lack of information. But feel free to re-open if there is something we could investigate.
