### ISSUE TITLE
Get new connection's IP address?

### ISSUE THREAD

**Issue by Niedzwiedzw** [snapview/tungstenite-rs#138]
I'm using websocket for IoT devices and I'd like to log the IP address for each connected device. How would I do that?

**Comment by application-developer-DA** [comment]
Well, strictly speaking it has nothing to do with `tungstenite`, it's about `TcpStream` from standard library (if you use one). It has `peer_addr()` and `local_addr()` functions. See [official Rust documentation](https://doc.rust-lang.org/std/net/struct.TcpStream.html) for this. But in case you're using Tokio you have to refer to the corresponding docs from Tokio docs.
