### ISSUE TITLE
Why does write_response use dynamic dispatch?

### ISSUE THREAD

**Issue by Redrield** [snapview/tungstenite-rs#141]
Is there any reason why handshake::server::write_response uses a trait object instead of an `impl Write` for its buffer parameter?

**Comment by application-developer-DA** [comment]
I don't see a reason why we need to use a dynamic dispatch there, but maybe there were some "historical reasons" for that. @agalakhov maybe you know it better than me?

**Comment by agalakhov** [comment]
It is definitely a leftover from early Rust versions.
