### ISSUE TITLE
Message length too big

### ISSUE THREAD

**Issue by iraizo** [snapview/tungstenite-rs#173]
thread 'main' panicked at 'Error trying to read message: Capacity("Message length too big: 21589869 > 16777216")', src\main.rs:42:41

`let msg = socket.read_message().expect("Error trying to read message");`

Is there any way to still read the message?

**Comment by application-developer-DA** [comment]
Sure. When you [connect to the server](https://docs.rs/tungstenite/0.12.0/tungstenite/client/fn.connect_with_config.html), you can specify [the config](https://docs.rs/tungstenite/0.12.0/tungstenite/protocol/struct.WebSocketConfig.html). The config contains a field which allows you to control the [maximum size of the message](https://docs.rs/tungstenite/0.12.0/tungstenite/protocol/struct.WebSocketConfig.html#structfield.max_message_size).

**Comment by iraizo** [comment]
works fine, but is there a way to read data in chunks so you can print them out bit by bit instead of waiting for the bytes to be done

**Comment by application-developer-DA** [comment]
What do you mean by "bit by bit"? If you need to read chunks from the TCP stream and print them, then you probably don't need WebSockets ;)

Reading from the stream is done inside of `tungstenite-rs`, i.e. we're reading into a buffer to gather the frames, which the message consists of.

**Comment by iraizo** [comment]
My issue fixed itself, i thought it was so long that it took minutes to read, but it didn't even get to the point of reading 🤦🏻‍♂️
