### ISSUE TITLE
Connecting to graphql requires specifying protocol.

### ISSUE THREAD

**Issue by mpbraendli** [snapview/tungstenite-rs#176]
Hi all,
I'm porting some code that's using https://github.com/websockets-rs/rust-websocket to tungstenite-rs, and I don't understand how I can negotiate the protocol.

I'm calling [add_protocol](https://docs.rs/websocket/0.26.2/websocket/client/builder/struct.ClientBuilder.html#method.add_protocol). Is there an easy way to do the same? Is that a duplicate of #145 ?

**Comment by application-developer-DA** [comment]
Yeah, [if I got your question right](https://tools.ietf.org/html/rfc6455#section-1.9), then you indeed can do this the way you referenced. The tracking issue is: https://github.com/snapview/tungstenite-rs/issues/107

I was not aware that the subprotocol for GraphQL is a mandatory thing, it seems like it was primarily mentioned here back in 2018: https://github.com/apollographql/subscriptions-transport-ws/issues/413

**Comment by mpbraendli** [comment]
#107 is about the server side, I should have mentioned that I'm doing a client connecting to a GraphQL subscription, that's why I referenced #145. I agree it's a duplicate.

**Comment by crajcan** [comment]
@mpbraendli you wouldn't happen to have any example code you could share for connecting a graphql subscription with tungstenite? You would be doing me a big favor.

**Comment by mpbraendli** [comment]
Sorry, in the end I didn't use tungestenite.
