### ISSUE TITLE
Duplex support in `WebSocket`

### ISSUE THREAD

**Issue by lemunozm** [snapview/tungstenite-rs#178]
Hi!

In a TcpStream, for example, I can perform a read/write operation at the same time from two threads. This is possible because these operations are non-mutable. I saw that `read_message`,  `write_message`, `write_pending` mutably borrow the `WebSocket`. Is there any workaround to perform these operations at the same time?

Thanks so much!

**Comment by strohel** [comment]
The general approach is to wrap the `WebSocket` in `Mutex<WebSocket>`, usually also in `Arc<...>`. That would resolve the "from two threads", but not the "at the same time" as the methods mentioned would block (current thread, and potentially also the other thread through the Mutex).

The "at the same time" could be in theory achieved by making the `TcpStream` [non-blocking](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_nonblocking). The Mutex would still be needed, but it should be locked only for very short periods. This method would require handling the WouldBlock errors.

**Comment by lemunozm** [comment]
Thanks, @strohel,  for your answer!

This is exactly what I am doing, a `Mutex<WebSocket>` with a non-blocking `TcpStream`. The problem I have appears when a sender bombards this socket. It is reading continuously and I have no time to send data by the writable side of the socket.

Any idea for this border case?

**Comment by agalakhov** [comment]
While you can do this using `Mutex`, a simpler approach exists. Let WebSocket belong completely to the reading thread. Use `mpsc` to send messages from the writing thread to the reading one.

If you don't want to handle non-blocking mode manually, look at `tokio_tungstenite`. One of its examples does exactly that.

**Comment by agalakhov** [comment]
You MUST use non-blocking connections if you want reading and writing at the same time.

`TcpStream` in blocking mode does not allow writing while reading regardless of WebSocket.

**Comment by lemunozm** [comment]
Thanks for the advice @agalakhov 

I will evaluate the `mpsc` option. Although because of the topology of my system, it will be difficult to fit it.

**Comment by agalakhov** [comment]
The solution that definitely would fit without great effort: make two instances of `mpsc`, one for sending and one for receiving, and a dedicated WebSocket thread.

**Comment by application-developer-DA** [comment]
I think that the original question has been answered, so I'm going to close this issue just to keep the issues list clean from resolved items ;)
