### ISSUE TITLE
Will tungstenite work on ios / iphone ?

### ISSUE THREAD

**Issue by gopakumarce** [snapview/tungstenite-rs#180]
Hi, 
I am writing an app for ios / iphone using rust and planning to use tungstenite. But before I proceed, I want to know if the native-tls flag will also support whatever is the native tls lib on iphone ? I do not want to package openssl with my app ! Please let me know

Rgds,
Gopa.

**Comment by strohel** [comment]
Hi, it is best to check Cargo.toml to see that the flag enables -> it pulls in the `native-tls` _crate_ -> please check that crate directly: https://github.com/sfackler/rust-native-tls (I don't know how well it works on iOS).

You may also want to check the recently added support for rustls. (again please check the upstream crate).
