### ISSUE TITLE
question: how to store the returned socket from connect ?

### ISSUE THREAD

**Issue by gopakumarce** [snapview/tungstenite-rs#181]
Sorry, I am relatively a rust newbie. the connect() API returns WebSocket<Stream<TcpStream, TlsStream<TcpStream>>> - and I want to store that in a structure. My VScode can figure out all the imports for WebSocket,Stream and TcpStream. But TlsStream - how  do I get that / what should I import for that ?

**Comment by gopakumarce** [comment]
never mind, I need to include native_tls in my cargo and stuff for that .. gaaah I wish rust was as simple as go in the matter of finding and including stuff without having coder spend 15 minutes trying to find how to include a defenition !

**Comment by application-developer-DA** [comment]
```
use tungstenite::{connect, WebSocket, client::AutoStream};

struct StoreMyWebSocket {
    ws: WebSocket<AutoStream>,
}
```

**Comment by gopakumarce** [comment]
thats super helpful ! Thanks a lot!
