### ISSUE TITLE
Question: Rx and Tx in parallel (from two threads)

### ISSUE THREAD

**Issue by gopakumarce** [snapview/tungstenite-rs#182]
Hi all,

Since the Websocket read_message and write_message takes an &mut self, there is no way we can do rx in one thread and tx in another if the rx is in blocking mode (if we protect websocket by mutex and for rx we take the lock and block, of course tx will block). But looking through the library, I guess for Tx, we can just clone the websocket and give a new structure and that should work fine ? Can someone please confirm that ?

Rgds,
Gopa.

**Comment by strohel** [comment]
Hi @gopakumarce, please check https://github.com/snapview/tungstenite-rs/issues/179 and https://github.com/snapview/tungstenite-rs/issues/178 which may answer your questions.

This seems to be a recurring question, so adding that to the documentation may be a good idea.

**Comment by gopakumarce** [comment]
thanks a lot!
