### ISSUE TITLE
Add a connector like in tokio-tungestenite

### ISSUE THREAD

**Issue by dnaka91** [snapview/tungstenite-rs#185]
While I implemented https://github.com/snapview/tokio-tungstenite/pull/147 I really liked the extra `*_tls*` functions that allow to pass a TLS connector. Not just because it allows to configure the connector details, but because it gives the chance to explicitly tell the crate what TLS implementation to use.

I thought that would be a nice addition for this crate as well to get the same benefits as these functions are currently not available here. That would mean to add `client_tls` and `client_tls_with_config` functions, a `Connector` and replacing `AutoStream` with `MaybeTlsStream`.

Just wanted to ask before I start implementing it and would like to hear opinion of the snapview team and community.

**Comment by strohel** [comment]
I do like the replacement of `AutoStream` with `MaybeTlsStream` - I believe it would solve problem that `AutoStream` API changes in non-additive manner then enabling feature flags.

Regarding `client_tls()` and `client_tls_with_config()` - it is already possible to use user-supplied stream with `client()` (like rustls one or openssl one) - so these would be in fact convenience wrappers? I would have to think more about that: we sort of mentally transition to consider `tungstenite` as a low-level "plumbing" and start to recommend `tokio-tungstenite` to people "by default". Which would speak against adding too much convenience to it.

What do you think, @application-developer-DA, @jxs?

**Comment by jxs** [comment]
Hi,
`tungsnite` might still have end user use cases, a little bit like [reqwest's blocking mod](https://docs.rs/reqwest/0.11.1/reqwest/blocking/index.html), and not only be only a low level crate for `tokio-tungstenite` so I would have them both with similar API's and add `client_tls()`  and `client_tls_with_config()`  to `tungstenite`. 
Also agree with you Matěj regarding the replacement of `Autostream`with `MaybeTlsStream` :+1:
