### ISSUE TITLE
How to send array buffers and not blob from a Tungstenite server to a JavaScript client?

### ISSUE THREAD

**Issue by LituDev** [snapview/tungstenite-rs#189]
Hey, even while sending binary from tungstenite, i keep receiving a blob i need to process on client side wich decreases performances. I would like to "directly" send an array buffer. Is there a way to fix that or is it a normal behaviour? Thanks! 
`let vec = vec![101, 10];
let message = Message::Binary(vec);
websocket.write_message(message).unwrap();`

**Comment by agalakhov** [comment]
There is no such thing as "ArrayBuffer" in Websocket standard. WebSocket deals with bytes.

Set `binaryType` to `arraybuffer` at client side. This should be enough.

**Comment by LituDev** [comment]
It works thanks!
