### ISSUE TITLE
Sock5 proxy support pull request

### ISSUE THREAD

**Issue by PrivateRookie** [snapview/tungstenite-rs#190]
Is there any work in process proxy support on this projects? 
I add client sock5 proxy support in my forked repo, and I am willing to port it back to source repo. But I can't find contribute doc on repo, and don't know whether any one is working on this  feature, should I create a pull request or waiting for other one's work?

here is quick link of my repo [sock5 proxy](https://github.com/PrivateRookie/tungstenite-rs/blob/f368f3087d50d97658fda5337550e587bb1ba1b6/src/client.rs#L229)

**Comment by application-developer-DA** [comment]
As far as I know, no-one works on the proxy support (no open PRs). [There is an issue](https://github.com/snapview/tungstenite-rs/issues/177) about proxy (not only SOCKS-5). I believe you know about it [as you've once commented there](https://github.com/snapview/tungstenite-rs/issues/177#issuecomment-798918074) ;)

The only issue is that as I noted in the comment it's probably not the job of tungstenite's to implement proxy support, tungstenite however may have a `proxy` feature that would use another crate to support proxy and different proxy authentication methods.

I'm going to close this issue as it seems to be a duplicate, but feel free to continue discussion in #177.
