### ISSUE TITLE
Consider replacement for the utf-8 crate

### ISSUE THREAD

**Issue by stanislav-tkach** [snapview/tungstenite-rs#197]
The `utf-8` crate is somewhat unmaintained (https://github.com/SimonSapin/rust-utf8/pull/6) and it lacks license files though the Apache-2.0 license requires it (https://github.com/SimonSapin/rust-utf8/issues/3). I would like to use the `tungstenite-rs` crate, but the company I'm working at doesn't permit using of crates without license.

I suppose even `std::str::from_utf8` can be used instead: `std::str::Utf8Error` provides the `valid_up_to` method which can be used to build a utf8 string from parts. This will require a little bit more code though.

**Comment by strohel** [comment]
Hi @stanislav-tkach.

If we can get completely rid of the `utf-8` dependency and provide equivalent functionality using just the standard library, that would be nice. Would you try to open a pull request for that? CC @application-developer-DA @jxs.

**Comment by stanislav-tkach** [comment]
@strohel Thank you for the quick response. Yes, I would like to deal with that.

**Comment by stanislav-tkach** [comment]
It is kind of awkward, but the `utf-8` crate has just has been updated to include licensed files. I guess this and the corresponding pull request can be closed. Sorry for bothering.

**Comment by application-developer-DA** [comment]
Alright, no problem.

(also it seems like the PR did not pass some tests: autobahn suite failed, so probably some investigations would have been required)
