### ISSUE TITLE
Questions regarding this crate

### ISSUE THREAD

**Issue by Joe23232** [snapview/tungstenite-rs#208]
Hi, I have some questions regarding this crate:
1. Can it be imported as a library with my existing code?
2. Is it like netcat?
3. Does this crate allows me to view the files from my PC to my other PC via the Internet and NOT through LAN, allows me to send over any files from my other PC to my PC (so like from my PC I can send a command to my other PC to send over certain files), allows me to send files back to the other PC, delete certain files etc?
4. If `3` is applicable, then lets say I have two other PCs on the same network and I opened up the exact same port on the two other PCs, if I wanted to remotely connect using my main PC from a different network, how would I know which PC to connect to?
5. Which program would I use to remotely connect from my PC to the other PC?

**Comment by agalakhov** [comment]
Hi,

1. It is to be used as a library with your existing code.
2. No, it is a library.
3. This crate is for network communication part ONLY. You can implement file transfer on top on this crate, but you have to do it yourself. 
4. Did you learn about IP addresses?
5. Did you learn about SSH?

**Comment by Joe23232** [comment]
Right i see, thanks mate
