### ISSUE TITLE
Simple API improvement

### ISSUE THREAD

**Issue by thomas-jeepe** [snapview/tungstenite-rs#21]
For the callback, something nice you can do is make the accept `Into<Option<Callback>>` and then you can pass the callback into it and it will get converted to the option if you do `let cb = cb.into()`.

Example:

```rust
fn print<T: Into<Option<&'static str>>>(str: T) {
    let str = str.into();
    match str {
        Some(str) => println!("{}", str),
        None => {}
    }
}

fn main() {
    print("hello");
    print(None);
}
```

https://play.rust-lang.org/?gist=ea5e776718d5338a0c0744e9e8e7d997&version=stable

Thats all.

**Comment by application-developer-DA** [comment]
We've changed the API since then (see https://docs.rs/tungstenite/0.5.0/tungstenite/server/fn.accept_hdr.html), so IMO this issue is not relevant anymore. Feel free to open a new one / reopen the existing one, if you think that there is something that can be improved in the current approach.
