### ISSUE TITLE
Bad performance with `input_buffer > 3.0` 

### ISSUE THREAD

**Issue by qiujiangkun** [snapview/tungstenite-rs#210]
The assembling process takes up most of the time in my IO thread. Why is it so slow? I would like to file an PR to improve it.
![image](https://user-images.githubusercontent.com/33482468/123516411-90731400-d6ce-11eb-9892-2dcacdd3363d.png)

**Comment by qiujiangkun** [comment]
Sadly, the performance of `input_buffer` is unacceptable.
https://github.com/qiujiangkun/input_buffer/blob/master/benches/read_data.rs
```log
Benchmarking throughput/decode: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 11.2s, or reduce sample count to 40.
throughput/decode       time:   [110.31 ms 110.61 ms 110.92 ms]                              
                        thrpt:  [216.37 MiB/s 216.98 MiB/s 217.58 MiB/s]
```
https://github.com/snapview/input_buffer/issues/6#issuecomment-869020368

**Comment by application-developer-DA** [comment]
Note that the provided custom "hack" version is essentially the same as older version of the `input_buffer` and the reason it was changed was that its implementation was unsound, so as maintainer I can't recommend using the "HACK" version right now.

Current state and discussion: https://github.com/snapview/input_buffer/issues/6#issuecomment-870548303

We're going to soon release the new version that is as safe as our current sound implementation but significantly faster.

**Comment by whyCPPgofast** [comment]
I see that input_buffer crate was updated and the bottleneck has been fixed. [https://github.com/snapview/input_buffer/pull/9](url)
Is it as simple as bumping the input_buffer version to 0.5.0 in tungstenite or is there more work to do? Thank you for the great library.

**Comment by application-developer-DA** [comment]
You're right, it was just about bumping the version of the dependency and releasing a new version. I decided to postpone it a bit, so that we can merge and release even better version that performs [even faster on average](https://github.com/snapview/tungstenite-rs/pull/214). I expect us delivering a new version tomorrow if the PR gets reviewed today.

**Comment by whyCPPgofast** [comment]
I see you updated the input_buffer crate and added benchmarks. Mind bumping the version of tungstenite-rs ? Thank you for the great work!
