### ISSUE TITLE
Handle ws response-reply + handle external events to send ws message

### ISSUE THREAD

**Issue by incker** [snapview/tungstenite-rs#220]
Hello,

    let (mut tx, rx) : (SplitSink<WebSocketStream<tokio::net::TcpStream>, tungstenite::Message>, SplitStream<WebSocketStream<tokio::net::TcpStream>>) = ws_stream.split();
    let tx2 = tx.clone();

I can not clone `tx` to make server initiate send messages in another thread. 

Or maybe you have a code example, best practices how to make both websocket responses and server initiation of send message on any external event. Or maybe code example in git

Forward thank you!

**Comment by application-developer-DA** [comment]
I believe you're using `tokio-tungstenite`, right? If so, I think it would be better to create the issue there, but it seems like your question is not related to `tungstenite-rs` or `tokio-tungstenite`, but rather to the basic Tokio usage. I may suggest getting familiar with the [Tokio tutorial](https://tokio.rs/tokio/tutorial) and/or ask for suggestions on the Discord channel ;)

As for examples: [we have some in the `examples` directory](https://github.com/snapview/tokio-tungstenite/tree/master/examples) in the `tokio-tungstenite` repository.
