### ISSUE TITLE
Extra header name incorrectly being lowercase

### ISSUE THREAD

**Issue by wuxianucw** [snapview/tungstenite-rs#224]
[`handshake/client.rs#L127-L133`](https://github.com/snapview/tungstenite-rs/blob/master/src/handshake/client.rs#L127-L133) in function `generate_request` (which I guess to be doing preparation work for the first HTTP request)

All of my extra headers' names become lowercase, maybe that's a wrong behavior?

**Comment by application-developer-DA** [comment]
Hm, interesting. I had a quick look, but it seems like it's not `tungstenite-rs`, since we explicitly check only one particular header without touching others. I believe that's either `RequestBuilder` that modified them or maybe you passed them initially as lowercase?

**Comment by wuxianucw** [comment]
> Hm, interesting. I had a quick look, but it seems like it's not `tungstenite-rs`, since we explicitly check only one particular header without touching others. I believe that's either `RequestBuilder` that modified them or maybe you passed them initially as lowercase?

Yes! I found `http` will convert it to lowercase, but I don't know how to recover them.

Inner the `http` crate, it seems that the header name will be mapped to a enum, which causes the unexpected lowercase.

**Comment by agalakhov** [comment]
IIRC, HTTP header names are defined to be case-insensitive and no software should rely on any particular case.

**Comment by application-developer-DA** [comment]
> Yes! I found http will convert it to lowercase, but I don't know how to recover them.
> Inner the http crate, it seems that the header name will be mapped to a enum, which causes the unexpected lowercase.

Ok, then I think I'm going to close the issue here in `tungstenite-rs`.

> IIRC, HTTP header names are defined to be case-insensitive and no software should rely on any particular case.

Right, it seems so, according to [the RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).
