### ISSUE TITLE
allow conecting to TLS servers that use a self signed certificate

### ISSUE THREAD

**Issue by jbtrystram** [snapview/tungstenite-rs#231]
Using 0.12 i have no issues conencting to a TLS server that uses self signed certificate. 
using 0.14 i get a handshake error. 
I understand the concern of self signed certs but it would be nicer to have a way to at least override it and print a warning .

**Comment by application-developer-DA** [comment]
In fact it's possible. Not sure [which of the changes](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md) caused the issue on your side, by default we never allowed to connect to the servers with the self-signed certificates. This is however was/still possible with the newest version that gives you the control over the `Connector` (hence the options, root certificate etc) ;)

**Comment by jbtrystram** [comment]
Ok thanks ! I had an handshake problem that was resolved by downgrading from 14 to 12, so i thought it was due to signed self certs. It was probably something different. 
Thanks for pointing me towards `Connector` i'll make sure to look into it
