### ISSUE TITLE
Potential memory leak on sender ? 

### ISSUE THREAD

**Issue by Lighty0410** [snapview/tungstenite-rs#237]
Hey everyone. First of all, thank you a lot for this amazing repo. 

The issue: 
I need to send binary data across clients. Each time a client connects to the websocket i accept the connection and start sending binary data to them without any bidirectional signal. And here comes the problems. The pipeline: 
1) Accept the connection. 
2) Start sending binary messages to the receiver. 
3) Resident memory of the application has grown by like ~50kb. 
4) Client closes the application on his side without any signaling with, for example, SIGINT (for some reason, i don' think signaling is the case).
5) The tokio task is over. 
6) However, resident memory consumption remains the same. After the client has disconnected there's NO expected resident memory usage dropdown. It seems like a certain buffer doesn't truncate (just an assumption).
 7) Repeat these steps and see how the application uses more and more memory (until OOM killer wouldn't kill it). 
 
 At first, i thought maybe there's some buffered info in the TCP sock. I tried to close the `ws_stream` using `.close()`. I tried to shut down the connection via `.get_mut().shutdown()`. Neither of them does anything, and both of them return all the same error - "broken pipe". At second i thought it's the allocator that doesn't return memory to OS. So i switched to jemalloc with some aggressive tuning and waited for almost an hour. 
 
 How i tested this behavior: 
 1) Run the [sender](https://gist.github.com/Lighty0410/f39980b34e67b6e775e4c1b13264dd01)
 2) Run the [receiver](https://gist.github.com/Lighty0410/842c35e0a3bfc9ecc739cf6b5680d72e)
 3) Optionaly apply aggressive tuning for jemalloc - `JEMALLOC_SYS_WITH_MALLOC_CONF="background_thread:true,narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true"`
4) Open htop.
5) Kill and run the receiver multiple times. 
6) Witness how the sender uses more and more memory while you repeat step 5. 

The question is. Is there anything wrong with the examples above ? Or i missed something ? 
Thanks in advance!

**Comment by application-developer-DA** [comment]
I'm going to close this as I started [the reply in the `tokio-tungstenite`'s duplicate](https://github.com/snapview/tokio-tungstenite/issues/195#issuecomment-925355813) that you created as it was related to some other Tokio topic ;)
