### ISSUE TITLE
Backpressure and monitoring load

### ISSUE THREAD

**Issue by gcandal** [snapview/tungstenite-rs#251]
As far as I understand, it's possible to cap the size of the send buffer, but is there an equivalent concept for reading, or is the size defined by the OS's socket buffet size?

Besides that, is there a way of knowing what are both the current size and capacity of the read and write buffers, in order to understand if either end (client/server) is not being able to keep up?

It's obvious by now, but I'll have to admit that I don't master these concepts, so I appreciate you reading this entire thing 👍

**Comment by application-developer-DA** [comment]
It is possible to specify [the maximum size of the message and the maximum size of the frame](https://docs.rs/tungstenite/0.16.0/tungstenite/protocol/struct.WebSocketConfig.html#structfield.max_message_size) (the message consists of one or multiple frames). We use some sane defaults there, but the user can limit it even more if it's desirable for a particular use case.

**Comment by application-developer-DA** [comment]
Hope the original question was answered ;)
