### ISSUE TITLE
Can we use tungstenite with actix-web?

### ISSUE THREAD

**Issue by kvzn** [snapview/tungstenite-rs#256]
How can we get stream implemented `std::io::Read`, `std::io::Write` from actix_web request?
```rust
#[get("/ws")]
pub(crate) async fn ws_index(req: HttpRequest, stream: web::Payload) -> Result<HttpResponse, Error> {
    let mut websocket = accept(stream).unwrap();
    
    loop {
        let msg = websocket.read_message().unwrap();
        if msg.is_binary() || msg.is_text() {
            websocket.write_message(msg).unwrap();
        }
    }
    
    Ok(HttpResponse::Ok().finish())
}
```

**Comment by application-developer-DA** [comment]
This is probably not required if you use the `tokio-tungstenite` (that is async-aware), e.g. you could use something like a [`WebSocketStream`](https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/struct.WebSocketStream.html) that does not require `Read` or `Write`, but instead `AsyncRead` and `AsyncWrite`.

**Comment by kvzn** [comment]
@application-developer-DA Do you know how we can get `AsyncRead` and `AsyncWrite` from http request of actix-web? 
Can't find it anywhere.

**Comment by application-developer-DA** [comment]
@kvzn, sorry, did not quite get the question. `AsyncRead` and `AsyncWrite` are normally the traits that are implemented for some sort of async-readable-writeable streams. If you have a stream that implements it, you could use it `tungstenite` with no issues :)

If you're concerned about the `Read + Write` vs `AsyncRead + AsyncWrite`, the "solution" (rather a workaround) that we came with in `tokio-tungstenite` is the following: https://github.com/snapview/tokio-tungstenite/blob/master/src/compat.rs
