### ISSUE TITLE
A Rust Beginner's Voice

### ISSUE THREAD

**Issue by aa51513** [snapview/tungstenite-rs#257]
First off, this is a whine from a beginner, no personal attack on anyone, just a simple whine.

By chance, I got to know the amazing language of rust, and I was amazed at its excellent memory management mechanism. It was such a simple reason that I decided to start learning it.

After learning the basic syntax and training many times, basically I can understand some Rust code, and I also decided to write a simple little tool for debugging programs.

However, just today, something shocked me: I can't get the ability to modify the http header in the existing library.

That means I'll either build the wheels myself (which is obviously not suitable for a beginner, and may take a long time to do), or just stare blankly.

As a programming developer for many years, I am very puzzled and puzzled why I simply want to modify the Host parameter in a Header, but I cannot support it, even mentioning the RFC standard

For this reason, I specifically checked the relevant RFC standards. In fact, there is no prohibition of doing so at all.

I suddenly felt that Rust would be too dogmatic and rigid and would not help me as much as I thought it would be?

_Originally posted by @application-developer-DA in https://github.com/snapview/tungstenite-rs/issues/255#issuecomment-1016628264_

**Comment by jxs** [comment]
Hi, this seems related with #255 so it makes sense to discuss there instead
Thanks!
