### ISSUE TITLE
Enable use of TcpStream::connect_timeout

### ISSUE THREAD

**Issue by tmsdev82** [snapview/tungstenite-rs#260]
Hi, 
First, thanks for such a wonderful and easy-to-use crate.

I have a case where I have a set of hosts where I want to connect to the first available one. Each resolving to a number of IPs. With the default time out on TcpStream it can take a very long time to go through all of them to reach one where a connection can be established.

I was wondering if it would be in scope for this crate to allow use of TcpStream::connect_time out in:
```rust
fn connect_to_some(addrs: &[SocketAddr], uri: &Uri) -> Result<TcpStream> {
    for addr in addrs {
        debug!("Trying to contact {} at {}...", uri, addr);
        if let Ok(stream) = TcpStream::connect(addr) {
            return Ok(stream);
        }
    }
    Err(Error::Url(UrlError::UnableToConnect(uri.to_string())))
}
```
Something like:
```rust
fn connect_to_some(addrs: &[SocketAddr], uri: &Uri, timeout: Option<Duration>) -> Result<TcpStream> {
    for addr in addrs {
        debug!("Trying to contact {} at {}...", uri, addr);
        if let Some(timeout) = timeout{
            if let Ok(stream) = TcpStream::connect_timeout(addr, timeout) {
                return Ok(stream);
            }
        } else {
            if let Ok(stream) = TcpStream::connect(addr) {
                return Ok(stream);
            }
        }
        
    }
    Err(Error::Url(UrlError::UnableToConnect(uri.to_string())))
}
```
Perhaps reachable through a new public fn tungstenite::connect_with_timeout(req,duration) -> connect_with_config() or something like that?

Kind regards,
Tim

**Comment by application-developer-DA** [comment]
Just connecting to the IP of the host that is available is already a part of [what `connect` does](https://docs.rs/tungstenite/latest/src/tungstenite/client.rs.html#59). Timeouts and other things are however not quite something that we would like to introduce (as it strictly speaking does not have anything to do with WebSockets), but these could be easily introduced in the user code, see: https://github.com/snapview/tungstenite-rs/issues/252

You could also take a look at `tokio-tungstenite` that together with Tokio gives more possibilities to customize the behavior, perhaps it would fit your use case a bit better.

Hope this helps :)
