### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by davidpdrsn** [snapview/tungstenite-rs#262]
I'm working on [updating axum](https://github.com/tokio-rs/axum/pull/753) to sha-1 0.10 but tungstenite (through tokio-tungstenite) still pulls in 0.9. It seems to have been fixed in `master` so any change you want to publish a new release?

**Comment by application-developer-DA** [comment]
Indeed, there have been several changes since the last version. Let me update the changelog and release it in the next few days.

**Comment by application-developer-DA** [comment]
Published.

**Comment by davidpdrsn** [comment]
> Though you would probably need `tokio-tungstenite` as well, right?

Probably but depends on how the semver requirements are setup between the two crates.

I'm afk right now but can test tomorrow.
