### ISSUE TITLE
Capturing identifiers in format strings break compatibility with rustc < 1.58

### ISSUE THREAD

**Issue by mfelsche** [snapview/tungstenite-rs#263]
This morning, upon upgrading to `0.17` our CI failed to compile with the following error log:

```
   Compiling tungstenite v0.17.0
error: there is no argument named `header`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tungstenite-0.17.0/src/handshake/client.rs:134:22
    |
134 |         write!(req, "{header}: {value}\r\n", value = value.to_str()?).unwrap();
    |                      ^^^^^^^^
 ```
 
We are still on rust `1.56.1` on our main branch, this is why this failed. We will switch soon, so this is not a biggie for us, but it would be nice, to have changes like this be guarded with a `MSRV` in your `Cargo.toml`. Should I add a PR for switching back to the old and painful way of handling format strings for increased compatibility?

**Comment by application-developer-DA** [comment]
Indeed. I think my preference would be us updating the `Cargo.toml` to specify the MSRV.

At the same time, I understand that other products may rely on an older version of the `rustc` for one reason or another. If needed, we could release a patch version (create a branch from the latest tagged release) that is backward compatible with the older compiler version.

However, if it's not a biggie for you (I suppose it's not based on your message 🙂), then I would prefer just mentioning the MSRV in our `Cargo.toml`.

**Comment by mfelsche** [comment]
That would be totally fine with me. Lets hope not too many downstream users are stuck with older rustc versions. If i may note that this is a very subtle way to bring people to the newest Rustc. ;-)

**Comment by application-developer-DA** [comment]
Alright 🙂 New version published.

**Comment by mfelsche** [comment]
Thank you so much!
