### ISSUE TITLE
tungstenite::connect keeps failing

### ISSUE THREAD

**Issue by kangalioo** [snapview/tungstenite-rs#269]
`tungstenite::connect()` fails with an HTTP 400 error, for multiple URLs, whereas all other websocket implementations I tried worked just fine.

main.rs:
```rust
fn main() {
    tungstenite::connect("wss://gateway.discord.gg/?v=9&encoding=json").unwrap();
}
```
Cargo.toml
```toml
tungstenite = { version = "0.17.2", features = ["rustls"] }
```
Error:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Http(Response { status: 400, version: HTTP/1.1, headers: {"server": "cloudflare", "date": "Sun, 27 Feb 2022 01:20:42 GMT", "content-type": "text/html", "content-length": "253", "connection": "close", "cf-ray": "-"}, body: None })'
```

Wit a different URL (`wss://demo.piesocket.com/v3/channel_1?api_key=oCdCMcMPQpbvNjUIzqtvF1d2X2okWpDQj4AwARJuAgtjhzKxVEjQU6IdCjwm&notify_self`, the demo URL from https://www.piesocket.com/websocket-tester), there's still an HTTP 400 error, except it comes from nginx instead of cloudflare. Something about tungstenite's request must be wrong, if all remote servers reject it.

Plugging those URLs into https://www.piesocket.com/websocket-tester or Python's websockets library works just fine.

**Comment by NotNorom** [comment]
I am running into the same problem. But when replacing `features = ["rustls"]` with `features = ["native-tls"]` it works for some reason.

**Comment by NotNorom** [comment]
Looks like 32450ae5af0070c7f3fd8341d244525119672506 changed the name of the rustls feature but didn't reflect those changes in the docs.

**Comment by application-developer-DA** [comment]
Ah right, we don't have the `rustls` feature anymore, we tried to reflect it in the [changelog](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md#0150), but perhaps we would need to mention it in the docs as well. Maybe failing with a different error when `wss` URL is used would be also an option. I hope the problem was solved after specifying one of the TLS feature flags 🙂

**Comment by application-developer-DA** [comment]
UPD. README has been updated.
