### ISSUE TITLE
Regression when connecting with a `http::Request` 

### ISSUE THREAD

**Issue by 1c3t3a** [snapview/tungstenite-rs#270]
Hi there! From the latest version on I get a regression when connecting with a `http::Request`. In version 0.17.1 I get an `WebsocketError(Protocol(InvalidHeader("sec-websocket-key")))` error when connecting via a Request, which worked back in earlier versions. Some example code to trigger the error (using tokio-tungstenite):

```rust
let mut req = http::Request::builder().uri(url.as_str());
let (ws_stream, _) = client_async(
            req.body(()).unwrap(),
            stream
        )
        .await?;
```

I looked into the issue and found out that the changes of PR #259 changed behavior for checking the key for a requests. In version 0.16.0 every request's `sec-websocket-key` header was set:
https://github.com/snapview/tungstenite-rs/blob/958fdb93d7d58cc65324a0e8eee01f515a67d284/src/handshake/client.rs#L55-L65
But the changes of PR #259 changed the behavior and now expect the `sec-websocket-key` header on every request:
https://github.com/snapview/tungstenite-rs/blob/45dad40cb544ac6bee91afb961a589938cbb514d/src/handshake/client.rs#L97-L122

This is fine for passing in a `Uri` or a `String` as the `IntoClientRequest` implementation covers the conversion:
https://github.com/snapview/tungstenite-rs/blob/45dad40cb544ac6bee91afb961a589938cbb514d/src/client.rs#L215-L238

But not for a `http::Request`. A possible solution would be to add the `sec-websocket-key` header in the implementation of `IntoClientRequest`, in case it is not yet present on a Request. Or is the intention that the user should provide it's own key when using a `http::Request` for connection?

**Comment by application-developer-DA** [comment]
The conclusions about [change in logic that we introduced](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md#0170) in `0.17.0` are correct 🙂

Essentially, if you're just simply using the `tungstenite`, e.g. you want to connect to an endpoint and use WebSockets, you could simply pass the URI and rely on the `IntoClientRequest` implementation that takes care of generating all required headers. But not when we receive `http::Request`, in which case we simply "pass-through" the request (after verifying that it's a correct request). Some rationale [could be found here](https://github.com/snapview/tungstenite-rs/pull/267#issuecomment-1046920524).

> Or is the intention that the user should provide its key when using a http::Request for connection?

Depends on your use case. If there is no strong reason to create a custom `http::Request`, you could simply pass ` &str` and benefit from `tungstenite` generating headers for you. In case you want to benefit from `tungstenite` generation of headers, but alter some of them, this could be a solution: https://github.com/snapview/tungstenite-rs/issues/264#issuecomment-1043322716

Hope this helps 🙂
