### ISSUE TITLE
Improve `Display` trait by formatting `Message` type as well

### ISSUE THREAD

**Issue by mishazharov** [snapview/tungstenite-rs#275]
Currently when writing code like this:

    incoming.try_for_each(|msg| {
        println!("Got a message {}", msg);

        future::ok(())
    }).await.unwrap();

I get output that kind of looks like this:

```text
Got a message hello
Got a message
```
The second message turns out to be a close message, but we can't tell based on the output of the display trait. This is because the display trait currently looks like this:
```
impl fmt::Display for Message {
    fn fmt(&self, f: &mut fmt::Formatter) -> StdResult<(), fmt::Error> {
        if let Ok(string) = self.to_text() {
            write!(f, "{}", string)
        } else {
            write!(f, "Binary Data<length={}>", self.len())
        }
    }
}
```
Essentially everything that isn't binary data can be turned into a string, and the string is sent to the formatter. Unfortunately the `Close`, `Ping`, and `Pong` messages do not usually contain bodies, so an empty string is sent to the formatter. I was curious if the maintainers would be open to a PR to change the `Display` trait to print something like this instead?
```text
{ type: [ Text | Ping | Pong | Close | Frame ], data: <text-data> }
```
or in the case of binary data:
```text
{ type: Binary, length: <length> }
```
If so I can make a PR, possibly depending on the [strum](https://docs.rs/strum/) crate to get the enum text.

**Comment by application-developer-DA** [comment]
Hm, the thing is that if we change the formatting of the text messages from the text to something like:

```
{ type: Text, data: "Hello World!" }
```

Then I bet most users will find it odd that a text message converted to text with `to_text()` returns an output that is akin to the output of the `Debug` 😉

OOC: Won't the usage of `Debug` solve the problem for your case? (e.g. `{:?}` instead of `{}` in the format string)

**Comment by mishazharov** [comment]
> Then I bet most users will find it odd that a text message converted to a text with `to_text()` returns an output that is akin to the output of the Debug :wink:

That's true, but my thinking was that since it would only be implemented for `Display` and not in `to_text()`

> OOC: Won't the usage of `Debug` solve the problem for your case? (e.g. `{:?}` instead of `{}` in the format string)

You're totally right though! This solves my issue. I guess I forgot about the debug trait. Thanks for helping!
