### ISSUE TITLE
Secure WSS connection with self signed certs

### ISSUE THREAD

**Issue by DerAndereAndi** [snapview/tungstenite-rs#276]
Hi everyone,

I am struggling to get tungstenite-rs working with either rustls or native-tls to connect to a host using a self signed certificate. The use case here is for offline IoT connections, where each device will require to use a self signed certificate and the connections need to be authorized by the user. The certs also won't have any DNS names but local IPs.

Is this even possible using tungstenite?

Thanks
Andreas

**Comment by agalakhov** [comment]
Hi,
yes, it is possible. You have three options.

First one and simplest one is, use native-tls and configure your OS to recognize your self-signed certificate (using control panel or whatever). If the certificate is recognized by your OS by default, so it will be with native-tls.

The second option is, connect to the server using rustls and pass the resulting stream to the `client_tls()` function. Look at its `ClientConnection::new()`. You have to provide `ClientConfig` with the proper certificate. The same is doable with `openssl`.

The third option is dangerous and not recommended but still possible. Configure your TLS library not to check certificate validity at all and provide your own callback for doing this. This is easily doable with openssl. If you do this, there are no security checks from the library, you're on your own.

I'd prefer the first way for corporate environments where the certificate could be easily installed by the system administrator, and the second way for software bundles for inexperienced users or for private use. If you choose the second or the third way, you don't have to enable TLS support in Tungstenite. Instead you perform the TLS connection in your code and pass to Tungstenite an already connected TLS socket.

**Comment by DerAndereAndi** [comment]
Hi @agalakhov 

thanks for your feedback! Much appreciated.

The first option sadly won't work. There is no such control over the OS and at the end I will need to create the certs dynamically on first run on the device itself. Also the device that I connect to, do the same and are from multiple different suppliers/brands. Think of heat pumps, washing machines, wallboxes, etc. pp.

rustsl also has issues with such certs right now as it won't have a DNS and also no trusted CA. The only way around I saw is to implement a custom cert verifier and (for now) simply accept them all. The trust chain is provided by the end user by pairing the two devices.

I did get to the step of creating a `ClientConfig` with a custom verifier. But I am a bit lost at connecting the bits here as a Rust beginner :( 

When using `rustls::ClientConnection::new()` it requires a dns name, but doesn't allow to provide an IP address, as far as I can see. So that won't work, right?

Regarding using `native-tls` instead, do you have a hint where I can find some example on how to configure not to check the validity?

**Comment by application-developer-DA** [comment]
Since version `0.15.0` (published 5 months ago) it is in fact even simpler since we allow users to specify their own connector in the [`client_tls_with_config()`](https://docs.rs/tungstenite/latest/tungstenite/fn.client_tls_with_config.html) function. This means that if you e.g. [use a `Connector` with the `NativeTls`](https://docs.rs/tungstenite/latest/tungstenite/enum.Connector.html) you can construct a [`TlsConnector`](https://docs.rs/native-tls/0.2.10/native_tls/struct.TlsConnector.html) while [specifying your own root certificate](https://docs.rs/native-tls/0.2.10/native_tls/struct.TlsConnectorBuilder.html#method.add_root_certificate) or [by disabling the validation](https://docs.rs/native-tls/0.2.10/native_tls/struct.TlsConnectorBuilder.html#method.danger_accept_invalid_certs) (probably not a good idea for production). Basically it would be a simplified version **of second and third options** that were suggested in the answer above.

**Comment by DerAndereAndi** [comment]
Thanks a lot @application-developer-DA 

So something like this should work? Or do you by chance see an error in my code?

```rs
    let connector = TlsConnector::builder()
        .danger_accept_invalid_certs(true)
        .build()
        .unwrap();

    let stream = TcpStream::connect("192.168.1.10:4712").unwrap();
    let connector: tungstenite::Connector = tungstenite::Connector::NativeTls(connector);
    let client = tungstenite::client_tls_with_config("wss://192.168.1.10:4712/", stream, None, Some(connector)).unwrap();
```

**Comment by application-developer-DA** [comment]
That's right, something like this should work.

But don't forget to activate the feature flag for the TLS, e.g. `native-tls` in case of your example.

See [list of TLS features](https://github.com/snapview/tungstenite-rs#features) in the README, it might be helpful.

**Comment by DerAndereAndi** [comment]
@application-developer-DA Thanks for all the help!

Sadly native-tls doesn't work for me, as the connection requires EDCSA algorithm which e.g. my dev system doesn't provide because of an old openssl.

So I need to try this with rustls again. The procedure would be similar?

**Comment by agalakhov** [comment]
Yes. It would be very similar. And, instead of accepting invalid certificates, you can add yours to the CA chain. This will make it valid.
