### ISSUE TITLE
How can I close a connection after split the stream?

### ISSUE THREAD

**Issue by whitelilis** [snapview/tungstenite-rs#278]
```
let ws_stream = accept_hdr_async(stream, handle_handshake(header_tx, peer))
        .await
        .expect("Failed to accept");
let (ws_out, ws_in) = ws_stream.split();
```
Then how can I close the connection when I got certain message?

**Comment by application-developer-DA** [comment]
For instance, [you could send a close message](https://docs.rs/tungstenite/latest/tungstenite/enum.Message.html#variant.Close) 😉 This will initiate and complete the "closing handshake" of the WebSocket as per RFC.
