### ISSUE TITLE
Update the documentation for `connect()` method to include the actual information of the TLS features

### ISSUE THREAD

**Issue by alpha-tango-kilo** [snapview/tungstenite-rs#280]
Hi there!

I've just started using Tungstenite and ran into an issue trying to support secure sockets.

The [documentation](https://docs.rs/tungstenite/0.17.2/tungstenite/client/fn.connect.html) says that to support WSS, you need to use `native-tls` or `rustls-tls` feature flags. I wanted to use the latter, but I noticed that the feature flag `rustls-tls`doesn't exist anymore. This led me to guess correcting it to `rustls`, which works because Cargo makes optional dependencies available as features implicitly (not something I'm a fan of, but here we are). However, this then meant that while everything compiled and ran, I would always have my connection refused with 400: bad request. Everything worked once I changed my feature selection to `rustls-tls-webpki-roots`, but it took a lot of head-scratching to work out that was the solution, as I hadn't used websockets before and didn't know what was going wrong (was it me, the API, or the library?).

A couple suggestions off the back of my experience, if I may:
* Update the [`connect` documentation](https://docs.rs/tungstenite/0.17.2/tungstenite/client/fn.connect.html) to include the up-to-date `rustls`-related feature flags
* Consider maybe triggering a compile error if compiling with not all the dependencies of a valid feature selection e.g. compiling with `rustls` but not `webpki`

I could look to write the PR if you'd like, just wanted to know your thoughts first :)

**Comment by application-developer-DA** [comment]
We've documented the usage of features [in the README](https://github.com/snapview/tungstenite-rs#features) 🙂 Unfortunately we've forgotten to update the documentation on `connect()`. E.g. we need to update it, thanks for noticing it.
