### ISSUE TITLE
Ability to disable automatic responses to ping frames

### ISSUE THREAD

**Issue by crowlKats** [snapview/tungstenite-rs#283]
From my testing, I found out that tungstenite automatically responds to ping frames with a pong frame, which is problematic for us as we need this not to happen for a test and specific behaviour. would it be possible to add some sort of config to `connect` to disable this, and to `from_raw_socket` as well?

**Comment by application-developer-DA** [comment]
The thing is that we do this to comply with the RFC that mandates replying to ping frames. If we did not do it, that responsibility would be on the shoulders of users, meaning that they must know the RFC well to implement the proper client (not only does this involve the replies on pings, but also things related to closing handshake, etc).

We currently don't support a flag that "turns off" the behavior of following the RFC.

OOC: Why would you need it? I mean, in case you have an automatic test suite that tests some business logic and you're not interested in pings and pongs, you can simply `match` the message and ignore ones that are irrelevant to your application.
