### ISSUE TITLE
What would be the minimal viable way to use tokio?

### ISSUE THREAD

**Issue by RobertRautenbach** [snapview/tungstenite-rs#293]
Apologies if you do not have time to answer beginner questions. Please feel free to close this issue if it is burdensome. 

I have read some simple examples provided in the [mio repo](https://github.com/tokio-rs/mio), in order to to create a non-blocking stream and queue up events. I then iterate over events and handle them. 
I set a timeout on how long `poll` will wait, so that I can send a ping request periodically(required for a project), if no events are present.
<details>
<summary>Reproduction: </summary>

```
use mio::net::TcpStream;
use mio::{Events, Interest, Poll, Token};
use tungstenite::accept;

use std::net::TcpListener;
use std::thread::spawn;
use std::time::Duration;

fn main() {
    let server = TcpListener::bind("127.0.0.1:3030").unwrap();
    for stream in server.incoming() {
        let stream = stream.unwrap();

        spawn(move || {
            let mut source = TcpStream::from_std(stream);

            const CLIENT: Token = Token(0);

            // Create a poll instance.
            let mut poll = Poll::new().unwrap();

            // Create storage for events.
            let mut events = Events::with_capacity(128);

            poll.registry()
                .register(&mut source, CLIENT, Interest::READABLE | Interest::WRITABLE)
                .unwrap();

            let mut websocket = accept(source).unwrap();

            // ping websocket on an interval
            let mut ping_timer = std::time::Instant::now();

            'outer: loop {
                poll.poll(&mut events, Some(Duration::from_secs(10)))
                    .unwrap();
                for event in events.iter() {
                    if event.is_read_closed() || event.is_write_closed() {
                        break 'outer;
                    }
                    if event.is_readable() {
                        if let Ok(msg) = websocket.read_message() {
                            match msg {
                                tungstenite::Message::Close(_) => {
                                    break 'outer;
                                }
                                tungstenite::Message::Text(text) => {
                                    println!("{}", text);
                                }
                                tungstenite::Message::Pong(_) => {
                                    println!("Pong received");
                                }
                                _ => {}
                            }
                        }
                    }
                }
                // Ping websocket
                if ping_timer.elapsed().as_secs() >= 10 {
                    ping_timer = std::time::Instant::now();
                    if websocket.can_write() {
                        websocket
                            .write_message(tungstenite::Message::Ping(vec![0x00; 8]))
                            .unwrap();
                    } else {
                        println!("Can't write to websocket");
                        break 'outer;
                    }
                }
            }
        });
    }
}
```
</details>

I am very new to rust, and I am still learning, which is why I haven't used  [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite) yet. Before I move on to using `tokio-tungstenite`, is anyone able to help me understand how one could implement a minimal viable `tokio` wrapper for `tungstenite`, instead of using `mio`, for my use case? I am seeking to understand how it is achieved and works before I jump in to using one that is already made. I have tried reading through the `tokio-tungstenite` source code, but rust is still a bit too new for me and I struggled to follow it.

Is it as simple as wrapping `let msg = websocket.read_message().unwrap()` in a future, then using a `tokio` thread to await the response? Or is it much more difficult than that?

Thank you for your valuable time.

**Comment by agalakhov** [comment]
Hi,
`tokio_tungstenite` IS the minimal viable `tokio` wrapper for `tungstenite`. Basically it just wraps `read_message()` in a future with correct error forwarding. To be more precise, this is a `Stream` and not just a `Future`. This is the actual wrapping: https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L273
As soon as you have the stream, you can iterate over it. Tokio provides necessary methods to do that.

There are many more other functions that are needed for completeness. For example, the initial handshake is wrapped too.

**Comment by RobertRautenbach** [comment]
Thank you very much for the explanation!
My question has been answered so this thread can be closed.
