### ISSUE TITLE
Rustls is not using HTTPS at all

### ISSUE THREAD

**Issue by illordlo** [snapview/tungstenite-rs#295]
Hi there,

I am new to Rust (hence, forgive me if I am wrong) but I am doing some test with `tungstenite-rs` with the following code:

```rust
fn main() {

    let (mut socket, response) =
        connect(Url::parse("wss://your-url-here").unwrap()).expect("Can't connect");

    println!("Connected to the server");
    println!("Response HTTP code: {}", response.status());
   
    loop {
        let msg = socket.read_message().expect("Error reading message");
        println!("Received: {}", msg);
    }
    //socket.close(None);
}
```

I added the following row to the `Cargo.toml` file:

```toml
tungstenite = {version = "0.17.3", features = ["native-tls"]}
```

and everything works. Unluckily, if I change `native-tls` to `rustls`, the requests are directed to port 443/TCP but are not encrypted at all (verified through packet sniffing).

If this is not due to a mistake on my side, it could be a problem if the server support both HTTP and HTTPS, because the client seems to work as expected but the traffic is in fact not protected by TLS.

Thanks in advance!

**Comment by application-developer-DA** [comment]
The reason it does no work with the `rustls` is that we don't have such feature 😉 

You can find the list of features [here in the README](https://github.com/snapview/tungstenite-rs#features).

If you try using `rustls-tls-native-roots` instead of `rustls`, it should work as anticipated.
