### ISSUE TITLE
SignalR websocket

### ISSUE THREAD

**Issue by chriseyhorn** [snapview/tungstenite-rs#307]
According to the SignalR protocol:

All JSON messages must be terminated by the ASCII character 0x1E (record separator).

Is there a setting to configure sending text messages to include the RS character or an example of how to do this?  When I try to add the character to the message, I'm getting an error: "Can't parse to JSON: Error("trailing characters")

Note: It shows as unknown below due to the GitLab editor here.

Example Code:

```
fn main() {

    let (mut socket, _response) = connect(Url::parse("ws://localhost:5189/hub").unwrap()).expect("Can't connect");
    
    let protocol = json!({
        "protocol": "json",
        "version": 1
    });

    socket.write_message(Message::Text(r#"{
        "protocol": "json",
        "version": 1
    }"#.to_string())).unwrap();

    loop {
        let msg = socket.read_message().expect("Error reading message");
        let msg = match msg {
            tungstenite::Message::Text(s) => { s }
            _ => { panic!() }
        };
        let parsed: serde_json::Value = serde_json::from_str(&msg).expect("Can't parse to JSON");
        println!("{:?}", parsed["result"]);
    }
}
```

**Comment by agalakhov** [comment]
This is not related to Tungstenite at all. If `serde_json` can't parse messages with extra 1E at the end, either remove this character or ask `serde_json` maintainers to support it.
