### ISSUE TITLE
Intigration with Oss-Fuzz

### ISSUE THREAD

**Issue by code-terror** [snapview/tungstenite-rs#309]
Hi @agalakhov and @application-developer-DA, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open-source projects.

As tungstenite-rs is  already cargo-fuzz based fuzzed, this makes it easily compatible with oss-fuzz out of box.

If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like
gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

As an alternative, if you don't have a google/gmail id, but still wish to integrate. I can add my mail id for time being and monitor bug/crashes.

Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

I personally have found many bugs with other open-source repositories.

**Comment by code-terror** [comment]
@agalakhov

**Comment by code-terror** [comment]
@agalakhov  Any thoughts?

**Comment by daniel-abramov** [comment]
Hey @code-terror, I'll try to substitute @agalakhov then 🙂

Are there any advantages of OSS-Fuzz over cargo-fuzz? - I have not compared them, but it looks like for generic fuzzing logic cargo-fuzz is just fine and covers almost all use cases we would love to cover.

**Comment by code-terror** [comment]
Hey @daniel-abramov , OSS-Fuzz is a free continuous fuzzing service provided by google. The project will be fuzzed by cargo-fuzz only but will be continuously fuzzed by oss-fuzz. They provide the infrastructure and have long runtimes to discover issues frequently. The code base of the project will still stay the same. 

Personally, many important bugs were found by oss-fuzz in the projects I was involved.

**Comment by daniel-abramov** [comment]
This sounds good, but I somehow don't get it how is it different from e.g. `cargo-fuzz` 🙂 Both `cargo-fuzz` and `OSS-Fuzz` perform fuzzing. Is `OSS-Fuzz` fuzzes things in some different way that makes it better at discovering bugs than `cargo-fuzz`?

It feels to me as it's like adding the support of `OSS-Fuzz` will essentially introduce another tool for doing the same job that `cargo-fuzz` does. I might be wrong though, that's why I'm trying to figure it out 😉
