### ISSUE TITLE
How can I write and read ws messages separately in two threads more efficient

### ISSUE THREAD

**Issue by dasauto2016** [snapview/tungstenite-rs#311]
I found a function called split() in https://github.com/snapview/tokio-tungstenite/blob/master/examples/client.rs
let (write, read) = ws_stream.split();
write and read helps to

But I didn't find a similar method in tungstenite-rs

Arc::new(Mutex::new(websocket)). The resulting Arc<Mutex<WebSocket<_>>> can be safely copied to other threads. 

But I feel that this operation does not need locks. Is there any more efficient way?

**Comment by dasauto2016** [comment]
Arc::new(Mutex::new(websocket)). The resulting Arc<Mutex<WebSocket<_>>> can be safely copied to other threads.

**Comment by agalakhov** [comment]
It doesn't exist and it can't exist. Use `tokio-tungstenite` unless you really know what you're doing.

**Comment by dasauto2016** [comment]
thanks a lot
