### ISSUE TITLE
How to accept on a non-blocking stream?

### ISSUE THREAD

**Issue by erenon** [snapview/tungstenite-rs#318]
Thanks for the nice library! I'd like to use `tungstenite-rs` `Websocket` `read_message` and `write_message` on a non-blocking TCP stream. The polling is implemented via `mio`, and all works fine, but the handshake. I found two options:

(1) Accept in blocking mode, switch to non-blocking mode after `tungstenite::accept`. (I know that this will block, but in this case this doesn't matter) The problem: tungstenite::accept takes ownership of the stream, therefore I have to pass the mio stream to it, that I'll use later. However, the mio stream doesn't have a `set_nonblocking` member:

```
let client: std::net::TcpClient = ...  // blocking by default
let mio_client = mio::net::TcpStream::from_std(client);
let mut ws = tungstenite::accept(mio_client).expect("accept");
ws.get_mut().set_nonblocking(true); // no such member
```

(2) Poll until accept finishes, on a non-blocking connection. The problem: how to continue the handshake after a potential block?

```
let client: std::net::TcpClient = ...  // blocking by default
client.set_nonblocking(true).expect("non-blocking");
let mio_client = mio::net::TcpStream::from_std(client);
let result = tungstenite::accept(mio_client);
match result {
  Ok(ws) => return ws; // ok, now we have an established connection?
  Err(e) => panic!("What now? How to turn e into something that can be used to continue the handshake?")
}
```

I could not figure it out from the doc or the source. (I checked the other tickets, and I know it works just fin with tokio, but I'm not interested in that) Thanks!

**Comment by erenon** [comment]
Note: with unsafe, a mio stream can be turned to be non-blocking (example is unix only):

```
fn set_mio_nonblocking(s: &mut mio::net::TcpStream) {
    use std::os::unix::io::AsRawFd;
    use std::os::unix::io::FromRawFd;
    let fd = s.as_raw_fd();

    let stream = unsafe { std::net::TcpStream::from_raw_fd(fd) };
    stream.set_nonblocking(true).expect("set_nonblocking client");
    std::mem::forget(stream); // do not close the fd
}
```

**Comment by agalakhov** [comment]
BTW, don't try to feed blocking streams to `mio`. It will harm the whole poll/select loop. If you really want to perform blocking operations first, do them in a separate thread, then switch the socket to non-blocking mode and send it to `mio` via `mpsc`. I did this in one of my projects, but one has to have a very good reason to go this way. Better switch everything to non-blocking immediately after creation.

**Comment by erenon** [comment]
Thanks!
