### ISSUE TITLE
dependency conflict about crate sha-1 v0.10.5

### ISSUE THREAD

**Issue by hhrrr** [snapview/tungstenite-rs#321]
As sha-1 has updated to v0.10.5 just now, the tungstenite-rs fails to compile.

error[E0432]: unresolved import `sha1`
  --> /Users/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tungstenite-0.17.3/src/handshake/mod.rs:15:5
   |
15 | use sha1::{Digest, Sha1};
   |     ^^^^ use of undeclared crate or module `sha1`
   |
help: there is a crate or module with a similar name
   |
15 | use sha_1::{Digest, Sha1};
   |     ~~~~~
For more information about this error, try `rustc --explain E0432`.
error: could not compile `tungstenite` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by newpavlov** [comment]
`sha1 v0.10.5` is yanked, so the issue should be resolved.

**Comment by franklinblanco** [comment]
`cargo update` to fix!

**Comment by hhrrr** [comment]
Thanks!
