### ISSUE TITLE
Improve adding custom headers

### ISSUE THREAD

**Issue by Taha-Firoz** [snapview/tungstenite-rs#327]
If you try to add custom headers to a connect request you can initialize a request object from the http crate, however this doesn't add the required ws headers like `sec-websocket-accept` and `upgrade` . The best way to add additional headers to a ws connect request is unnecessarily complicated.

```
            let mut request = WS_URL.into_client_request().unwrap();
            request.headers_mut().insert("User-Agent", "Some-custom/UserAgent".parse().unwrap());
```
This is the only method that allows the socket to actually connect, maybe the request builder can be exposed optionally that adds the necessary headers added by the `into_client_request` implementation for `URI`?

**Comment by daniel-abramov** [comment]
What would the API look like?

Currently, we basically provide two simple ways to create a proper request:

1. Just specify the URL (the most trivial use-case that the majority of users use) and `tungstenite` will construct all the necessary headers.
2. Allow user to use their own request, in which case `tungstenite` does not intervene with the user-defined headers and the values that are set there, but only checks it for sanity (i.e. rejects requests that don't have minimal correct headers).

In both cases, the user can change the request before passing it to `tungstenite`. The reason why (2) does not generate any WebSocket headers is that doing so by default would introduce a [possibly undesired] side-effect of changing the user's request, i.e. if a user passes a custom HTTP request, we assume that they know what they are doing and probably have a strong reason to do so which means us modifying the request (possibly overwriting some user headers related to WebSocket that might have been set) would not be a good thing.

So I'm not sure I understood the problem. I think that if you're constructing a custom HTTP request or getting it from somewhere before passing it to `tungstenite`, you have full control over what the request contains. Whereas if you just want a simple WebSocket request but want to add one or two headers, then you can always use the `.into_client_request()` and use `headers_mut()` to insert additional headers (I don't find it "unnecessarily complicated" to be honest 🙂).

**Comment by SixoneKui** [comment]
many thanks
