### ISSUE TITLE
rustls-tls-native-roots and rustls-tls-webpki-roots features don't compile

### ISSUE THREAD

**Issue by mlemesle** [snapview/tungstenite-rs#344]
Hey there !

I noticed that `rustls-tls-native-roots` and `rustls-tls-webpki-roots` features don't compile on master.
I'll submit a PR soon.

After that, will it be possible to publish a version of tungstenite to benefit from the latest dependencies version bumps please ?

**Comment by daniel-abramov** [comment]
Oh, that might have gotten broken after the update of the crate, our CI pipeline has not caught this error somehow. Thanks for the PR!
