### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by mlemesle** [snapview/tungstenite-rs#346]
Hey there !

Thanks for timing the time to merge my previous PR!

Do you think that making a new version is possible ? I stumbled upon some errors because of dependency versions.

That'd be amazing !

**Comment by daniel-abramov** [comment]
Sure, I'll try to get to my development laptop over the easter holidays to update the changelog and publish a new version.

**Comment by mlemesle** [comment]
That'd be amazing, thanks !

**Comment by daniel-abramov** [comment]
Done. Sorry for the delay.

**Comment by mlemesle** [comment]
No worries, thanks for the effort !
