### ISSUE TITLE
TODO in code: replace copy_nonoverlapping() with read_unaligned()

### ISSUE THREAD

**Issue by Shnatsel** [snapview/tungstenite-rs#35]
There is a TODO in the code: "replace this with read_unaligned() as it stabilizes"

https://github.com/snapview/tungstenite-rs/blob/3abe419/src/protocol/frame/mask.rs#L31

`read_unaligned()` has been [stabilized](https://doc.rust-lang.org/core/ptr/fn.read_unaligned.html) in Rust 1.17

Also of interest, `to_bytes()`/`from_bytes()` which seems to be the safe equivalent of what the unsafe code is doing here, is going to be [stabilized](https://github.com/rust-lang/rust/issues/49792) in Rust 1.29, which is the next release.

**Comment by agalakhov** [comment]
Thank you!

**Comment by bluetech** [comment]
Just passing by, but I wonder why is `read_unaligned` needed? The `&mask` reference should be sufficiently aligned, according to the reference at least: https://doc.rust-lang.org/reference/type-layout.html

**Comment by agalakhov** [comment]
The `&mask` has an alignment of just `u8`, and the one of `u32` is needed.

**Comment by bluetech** [comment]
Yes, you are correct, I misread:

> An array of `[T; n]` has a size of `size_of::<T>() * n` and the same alignment of `T`.

Maybe it's better to just read a `u32` off the wire and work with that, like actix does.

**Comment by agalakhov** [comment]
Working with `u32` requires endianess-dependent code. The behaviour is defined by RFC for `u8`, not for `u32`. On an unusual CPU or in a critical environment one could disable unsafe optimizations and stick to straightforward `apply_mask_fallback` which is definitely correct.
