### ISSUE TITLE
Consider supporting buffer types other than `Vec<u8>` for binary `Message`s

### ISSUE THREAD

**Issue by chuigda** [snapview/tungstenite-rs#353]
I *personally* want to get a *somewhat more aligned* buffer for received binary messages somehow, in order to do some *in-place dirty dirty things*. and I *guess* there should be some real world use cases. I wonder if such feature can be added, or if there could be some workarounds.

---
An alternative option, *as far as I've considered*, is to utilize the [allocator_api](https://github.com/rust-lang/rust/issues/32838) but it's still unstable.

**Comment by daniel-abramov** [comment]
It seems like it's having a broad overlap with https://github.com/snapview/tungstenite-rs/issues/96 and the corresponding PR, i.e. we thought about changing the underlying type for the `Message` to not enforce owned data when calling `write_message()`. This won't quite work with any data type that you've mentioned ("in place dirty dirty things" 😉 ).

Or, to be more precise, there have been discussions around splitting the sans I/O part of the library into `tungstenite-core` that is generic over the data (read accepts a buffer, write accepts a buffer also, no I/O on streams) and then make `tungstenite` and `tokio-tungstenite` wrappers around it. But we have not come up with a plan (though PRs or changes in this direction are welcome).
