### ISSUE TITLE
On the issue of websocket blocking reads

### ISSUE THREAD

**Issue by eagle-1949** [snapview/tungstenite-rs#388]
I know that read is blocked, and now I want to send a message to websocket after reading in the loop. However, due to read blocking, the subsequent code cannot be executed. Is there a good solution?
`thread::spawn(move || {
        loop {
            // If the code socket.read() is blocked, it cannot reach here
            if let Ok(data) = text_receiver.try_recv() {
                socket.send(Message::Text(data)).unwrap();
            }
            let msg_res = socket.read();
            match msg_res {
                Ok(msg) => {
                    println!("Received: {}", msg);
                    match msg {
                        Message::Text(m) => {
                            println!("receive mesg {:?}", m);
                            sock_sender.send(m).unwrap();
                            notice_sender.notice();
                        }
                        Message::Binary(m) => {
                            println!("receive mesg {:?}", m);
                        }
                        Message::Ping(m) => {
                            println!("receive ping mesg {:?}", m);
                            socket.send(Message::Pong(m)).unwrap();
                        }
                        Message::Pong(_) => {
                            println!("receive pong message");
                        }
                        Message::Close(m) => {
                            println!("receive mesg {:?}", m);
                            socket.close(None).unwrap();
                            wsclose_sender.notice();
                            break;
                        }
                        Message::Frame(m) => {
                            println!("receive mesg {:?}", m);
                        }
                    }
                }
                Err(e) => println!("get err {}", e),
            }
        }
    });`

**Comment by eagle-1949** [comment]
If the TCP stream can be split for sharding, then I can use two threads to read and write separately. This can solve the problem perfectly, but unfortunately it does not support split

**Comment by agalakhov** [comment]
Indeed there is a good solution. It is on the operating system level. By default TCP streams are usually blocking, but virtually all systems support switching them to non-blocking mode. In this mode neither `read` nor `white` block. They return immediately if the socket can not be read or written.

Tungstenite _does_ support non-blocking streams. Just switch the `TcpStream` to non-blocking mode.

However, the non-blocking mode is tricky on its own. You have to manually wait for incoming data or else you get 100% CPU load by repeatedly trying to read what can't be read. There is a library doing that, it is called `Tokio`. And there is a binding for using Tungstenite with it, called `tokio-tungstenite`.

If you decide to split TCP stream, **do not** wrap it in Tungstenite _after_ splitting. This won't work. WebSockets must read _and_ write while reading. Splitting is always done afterwards. Take a look at `tokio-tungstenite` or `async-tungstnite` source code.
