### ISSUE TITLE
New release for working with Http 1.0?

### ISSUE THREAD

**Issue by andyquinterom** [snapview/tungstenite-rs#389]
I'm working on a project right now, using hyper 1.0 and therefore http 1.0. A new release for tungstenite and maybe Tokio-tungstenite would make life much easier.

Is there a roadmap for a new release?

**Comment by agalakhov** [comment]
Maybe we can release right now, I'll look at it. We already have 1.0 in master. Does the master version work for you?

**Comment by andyquinterom** [comment]
Master works perfectly for my use case. Just tried it alongside `tokio-tungstenite` and now I have no problems :)

**Comment by andyquinterom** [comment]
Any updates on this? Is there any way I can help?

**Comment by agalakhov** [comment]
I just published v0.21.0. Enjoy :)

**Comment by andyquinterom** [comment]
> I just published v0.21.0. Enjoy :)

🎉🎉🎉🎉 Amazing thank you so much

**Comment by alexheretic** [comment]
We should also update the changelog now a new release is out
