### ISSUE TITLE
Consider merging tungstenite-rs and tokio-tungstenite repositories

### ISSUE THREAD

**Issue by nox** [snapview/tungstenite-rs#4]
Cargo is able to let users manage multiple related crates from a single repository, and this makes development of closely-related crates quite easier. See serde, url and webrender for examples of such projects.

**Comment by application-developer-DA** [comment]
I don't think it makes sense. Take a look at `native-tls` and `tokio-tls`, `rust-openssl` and `tokio-openssl`, `redis-rs` and `tokio-redis`, this is the model we followed. The base library (`tungstenite-rs`) gives you an efficient stream-based WebSocket library, which can be used on its own, it also provides a convenient abstractions to those ones who want to build their own wrapper/library for handling their specific use cases; for instance `ws-rs` can be rewritten on top of `tungstenite-rs` in a way that the public interface of `ws-rs` remains untouched, but the code/backend uses `tungstenite-rs`. Would it mean that `ws-rs` has to become a part of the `tungstenite-rs` repository in such case? - I don't think so.

So the way it's managed now is quite flexible and simple. The same with tokio bindings - `tokio-tungstenite` is a library written by us which relies on `tungstenite-rs`, but if some day someone from `tokio-rs` maintainers like Alex Crichton (or anyone else) decides to write his own tokio version, he can easily do it on top of `tungstenite-rs` without using the existing `tokio-tungstenite` and without the need to merge his repository (which most likely would be placed inside the `tokio` community repositories) inside `tungstenite-rs` (it was just an example, in fact Alex Crichton is aware about our library and he has already made a quick review of it and gave a useful feedback).

**Comment by nox** [comment]
@application-developer-DA Seems fair.

Btw I hope I'm not bothering you with them issues. I guess now you have a bunch of closed issues to link to in case someone else ask the same question. :)

**Comment by agalakhov** [comment]
@nox Thank you for your questions, it's really important for us to get a feedback.
