### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by Its-Just-Nans** [snapview/tungstenite-rs#409]
Hello,

Is it possible to create a PR to bump the version to release the header upgrade ?

Or should I wait for https://github.com/snapview/tungstenite-rs/pull/363 to be merged (then the version will be hopefully upgraded) ?

**Comment by daniel-abramov** [comment]
Hm, I don't have a strong opinion on that, but it looks like the change introduced in https://github.com/snapview/tungstenite-rs/pull/400 is the only one since the latest release. Let's see if there is any progress on #363 if that's fine.
