### ISSUE TITLE
Remove or make even more optional the `url` crate in the next version. 

### ISSUE THREAD

**Issue by Thomas-airmatrix** [snapview/tungstenite-rs#412]
Outside of tests there is only a single use of `url::Url` in tungstenite:
```rust
impl<'a> IntoClientRequest for &'a Url {
    fn into_client_request(self) -> Result<Request> {
        self.as_str().into_client_request()
    }
}

impl IntoClientRequest for Url {
    fn into_client_request(self) -> Result<Request> {
        self.as_str().into_client_request()
    }
}
```
Which is just implementing some helper conversion traits.

Instead, we can just have users call `as_str()` on the Url directly if needed.

With `http` =1,  `http::uri::Uri` has replaced most uses of the `url` crate. I have multiple project such that the only use of `url` is tungstenite.

**Comment by Its-Just-Nans** [comment]
This can be closed ?!
