### ISSUE TITLE
TLS support for non-blocking client

### ISSUE THREAD

**Issue by TechnoPorg** [snapview/tungstenite-rs#429]
I am investigating making `wss://` connections using tungstenite, for the sake of https://github.com/lemunozm/message-io/issues/102.
Based on that issue, it seems that this crate does not support client-side TLS when using the `tungstenite::client` function to connect to a server.
It seems as though the blocking/non-blocking websocket connections should have feature parity, but since this currently isn't working, is there any workaround?

**Comment by daniel-abramov** [comment]
TLS does not depend on the mode (blocking/non-blocking) of a socket.

`client()` function has never had any additional (TLS or other) logic. It only deals with the WebSocket connection.

[`client_tls()`](https://docs.rs/tungstenite/latest/tungstenite/fn.client_tls.html) is the TLS counterpart.
