### ISSUE TITLE
How to handle authentication?

### ISSUE THREAD

**Issue by DJDuque** [snapview/tungstenite-rs#447]
Would it be possible to add an example that shows how to handle authentication?

I am probably doing something wrong, but following the `client` example I am trying to do something like:
```rust
use anyhow::Context;

fn main() -> anyhow::Result<()> {
    // This works
    let body = reqwest::blocking::get("https://user:password@server.com/something")
        .context("failed to get response")?
        .text()?;

    // This doesn't
    let (mut socket, response) =
        tungstenite::connect("wss://user:password@server.com/something/ws")
            .context("failed to connect to websocket")?;

    Ok(())
}
```

I am pretty sure it is not an issue in the server side, because I can successfully do this with python's `websockets` library:
```python
url = f"wss://{user}:{password}@server.com/something/ws"
ssl_context = ssl._create_unverified_context()
async with connect(url, ssl=ssl_context) as websocket:
    # Send stuff here...
```

**Comment by agalakhov** [comment]
Authentication is currently outside of Tungstenite's scope. You need something like https://crates.io/crates/http-auth to authenticate. The connection can be passed to Tungstenite after successful authentication by calling `client()`.

**Comment by DJDuque** [comment]
In case someone is here from the future, after some playing around I figured that all I needed was just:
```
let uri: tungstenite::http::Uri = "wss://server.com/ws".parse()?;
let builder = ClientRequestBuilder::new(uri)
    .with_header("Authorization", "Basic BASE64_ENCODED_USER_PASSWORD");
let (mut socket, response) = connect(builder).context("failed to connect")?;
```

Feel free to close this issue.
