### ISSUE TITLE
`tungstenite::client::connect` on http(s) url

### ISSUE THREAD

**Issue by alex-kattathra-johnson** [snapview/tungstenite-rs#451]
Can we allow connect to http(s) url for endpoints that are upgraded?

**Comment by daniel-abramov** [comment]
`connect()` works for both HTTP and HTTPS URLs (provided TLS features are enabled).

If by "endpoints that are upgraded" you mean running `tungstenite` over the stream that has already been upgraded to a WebSocket connection, then you can use one of the following functions:

- [`WebSocket::from_raw_socket`](https://docs.rs/tungstenite/latest/tungstenite/protocol/struct.WebSocket.html#method.from_raw_socket)
- [`WebSocket::from_partially_read`](https://docs.rs/tungstenite/latest/tungstenite/protocol/struct.WebSocket.html#method.from_partially_read)

**Comment by alex-kattathra-johnson** [comment]
We we throw an error here for everything that isn't wss or ws. Would be nice if we could allow `http` and `https` which could be upgraded into websocket at handshake.
https://github.com/snapview/tungstenite-rs/blob/master/src/client.rs#L148

**Comment by alex-kattathra-johnson** [comment]
Updating the `scheme` to `ws`/`wss` fixed my specific issue with the kubernetes `watch` API, FWIW. We can close this issue if we find that allowing non-ws scheme in a websocket client is against the RFC guidelines.

**Comment by agalakhov** [comment]
Agree, but this has to be feature-gated. There are potential use-cases where it could be unexpected and even security critical, mostly if the address comes from an user input field.
