### ISSUE TITLE
Handling of HTTP-redirects (follow HTTP 3xx redirects)

### ISSUE THREAD

**Issue by shmutalov** [snapview/tungstenite-rs#46]
How to handle HTTP redirects? I am trying to connect to gitter API with no success:
https://github.com/shmutalov/gitter-rs/blob/develop-streaming/faye/src/lib.rs#L71

**Comment by bsergean** [comment]
This was filed here too -> #139

**Comment by Redrield** [comment]
If this is something that the maintainers would be fine with making a special case for, I can implement it

**Comment by application-developer-DA** [comment]
I'm a bit indifferent :) But if it does not bring any adverse side effects, then why not?

@agalakhov, what do you think?

**Comment by application-developer-DA** [comment]
Fixed by #148
