### ISSUE TITLE
Accepting new connections from a non-blocking socket

### ISSUE THREAD

**Issue by richerarc** [snapview/tungstenite-rs#47]
Is there a way to accept a connection from a non-blocking tcp listener (like those of Mio)? For all I know, either I call accept on a blocking tcpStream, or I can use `WebSocket::from_ram_socket`, but creating a websocket this way won't handle any handshake msg..

Thx!

**Comment by agalakhov** [comment]
Yes, Tungstenite is intended to be used with non-blocking listeners. In the handshake stage it returns "would block" with incomplete handshake state as an error. Refer to the sources of `tokio-tungstenite` for examples.

**Comment by application-developer-DA** [comment]
I believe that the questions has been answered, so I'm closing this issue right now. Re-open it in case if something is still not clear from the documentation.
