### ISSUE TITLE
Re-Connect client socket

### ISSUE THREAD

**Issue by tnpxu** [snapview/tungstenite-rs#49]
sometime i got issue when connect to websocket (connection lost) , Is there any solution regarding auto re-connect websocket

**Comment by agalakhov** [comment]
Just connect again. There is nothing special about reconnect.

**Comment by application-developer-DA** [comment]
NB: Might be helpful https://github.com/snapview/tungstenite-rs/issues/32 (similar question, regarding the reconnection).
