### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by emschwartz** [snapview/tungstenite-rs#50]
Would it be possible to publish a new version of the crate? I have code that's dependent on https://github.com/snapview/tungstenite-rs/commit/da85989934be3f5d992f4db5dd5d608091c1b005 and I can't publish my crate until there's a new version of this crate (and `tokio-tungstenite` that uses the next version of this crate).

Thank you!

**Comment by agalakhov** [comment]
Sure.

**Comment by agalakhov** [comment]
Released the version. Tokio-tungstenite seems to pick up the new version automatically.

**Comment by emschwartz** [comment]
Thanks!
