### ISSUE TITLE
How to track identity between handshake callback and ws stream?

### ISSUE THREAD

**Issue by totorigolo** [snapview/tungstenite-rs#57]
Hi!

I am building a game server, and I am passing the auth token as a handshake header. I am checking the token during the handshake to reduce the impact of DoS attacks and to simplify the logic afterwards (the user is auth'ed, no need of a state machine). However, I would like to have access to the token after the handshake, or to the socket address in the callback.

Is that currently possible?

**Comment by application-developer-DA** [comment]
Hi,

the `accept_hdr()` function allows you to specify an object (callback), which will be called as the request is received, you can analyse the headers in this callback and save some of them for a later use if required.

**Comment by totorigolo** [comment]
Thanks for the prompt answer! I knew about the callback, but since I used it as a shared data structure containing immutable sets of allowed hosts and paths and mutable (mutex) map of (allowed tokens, ID), I forgot that it was indeed a new callback for each connection. I remembered it when I noticed that the callback consumes self and is thus `FnOnce`.

I solved my issue by giving the peer address and a oneshot chanel to the callback. Then I wait for the data in oneshot in a `and_then` after `accept_hdr_async(stream, handshake_callback)`. Here is the code, if it can help someone:

```rust
let (user_id_oneshot_tx, user_id_oneshot_rx) = oneshot::channel();
let handshake_callback = HandshakeCallback::new(user_id_oneshot_tx, shared_data.clone());

accept_hdr_async(stream, handshake_callback)
    .map_err(WebSocketServerError::ConnectionRefused)
    .and_then(move |ws_stream| {
        user_id_oneshot_rx
            .map_err(WebSocketServerError::OneshotClosed)
            .map(|user_id| (ws_stream, user_id))
    })
    .and_then(move |(ws_stream, user_id)| {
        // ...
    })
```
