### ISSUE TITLE
Support non-blocking synchronous servers

### ISSUE THREAD

**Issue by peterfifthrow** [snapview/tungstenite-rs#61]
I can't see a non-blocking alternative to `server::accept`, e.g. something like `try_accept`. It doesn't seem to be possible to build a server that runs in just a single thread.

**Comment by peterfifthrow** [comment]
Ah, I can just work directly with `std::net::TcpStream`s and construct `WebSocket`s from those, perhaps?

**Comment by application-developer-DA** [comment]
It is. Actually it depends on the type of the underlying stream you use. It might be non-blocking (as mentioned in the docs).

If you want to write a server using non-blocking API, you'll either have to implement it on top of [mio](https://github.com/tokio-rs/mio) crate which provides you non blocking APIs, or [more likely] you'll want to take a look at [tokio](https://tokio.rs/) which is now almost a standard for async-like clients and servers. In this case we even provide a library which wraps the `tungstenite-rs` and makes it ready for usage inside `tokio`: https://github.com/snapview/tokio-tungstenite

**Comment by application-developer-DA** [comment]
> Ah, I can just work directly with std::net::TcpStreams and construct WebSockets from those

Absolutely, but I don't think it makes sense as `tungstenite-rs` examples use the tcp streams from standard library. If you want to go async, there are basically 2 options available (mentioned above).

**Comment by application-developer-DA** [comment]
Here is an example of fully working non-chat server based on tokio: https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs

**Comment by peterfifthrow** [comment]
Thanks. I think we want to avoid adding a runtime. But it looks like the main homepage example should work fine if I just set the `TcpListener` to non-blocking. I can run everything in one loop then.

**Comment by application-developer-DA** [comment]
Yeah, if you use the non blocking stream, it will work just fine, but return `WouldBlock` if the stream would block. But you'll have to have your own runtime to handle this anyways, because if you're going to use `mio` crate, you'll have to implement the whole thing on your own (polling open connections etc).

**Comment by application-developer-DA** [comment]
It seems that the original question has been addressed, so I'm closing this issue.

**Comment by agalakhov** [comment]
Yes, you can just set `TcpListener` to non-blocking. The `WouldBlock` error will be then returned correctly if the connection is not ready.
There is no need for a runtime, kind of. To be more precise, you can use your own runtime like polling multiple streams at once in `mio` loop. That's exactly what we do in our production, so this mode is well-tested.
