### ISSUE TITLE
Publish v0.9.0 on crates.io

### ISSUE THREAD

**Issue by SimonSapin** [snapview/tungstenite-rs#65]
… with https://github.com/snapview/tungstenite-rs/pull/63. This would allow deduplicating the `url` crate in Firefox. Thanks!

**Comment by SimonSapin** [comment]
Hi @agalakhov, could you help with this? It would help unblock some other work. Alternatively, would you be open to give crates.io publication access to a few other people you trust, so they can take care of it? This is done by running `cargo owner -a GithubUsername tungstenite`.

**Comment by agalakhov** [comment]
Hi, will be done today.

**Comment by agalakhov** [comment]
Done.

**Comment by SimonSapin** [comment]
Thank you!
