### ISSUE TITLE
How do I extend the server.rs example to echo each message to all currently connected users?

### ISSUE THREAD

**Issue by the-bass** [snapview/tungstenite-rs#69]
I can imagine this is rather a beginner's question for most of you, so I apologise to bother you with that.

A simplified version of what I'm trying to do is to extend [the server.js example](https://github.com/snapview/tungstenite-rs/blob/master/examples/server.rs) to forward each incoming message to _all_ currently connected users, instead of just the one user that has sent the message.

In my own attempts I always failed at the fact that a mutable version of the `websocket` is in use in a never-ending loop to listen to incoming messages, using `websocket.read_message()`. And so I wasn't able to have another mutable version of it in another thread to distribute the messages using `websocket.write_message(msg)`.
Usually, when I need to share mutable variables across threads, I use `Arc` and `Mutex`, but in this case this only leads to the `websocket` forever being locked in the `websocket.read_message()`-loop.

Does anyone have a suggestion on how to solve this problem?

**Comment by application-developer-DA** [comment]
> Usually, when I need to share mutable variables across threads, I use Arc and Mutex, but in this case this only leads to the websocket forever being locked in the websocket.read_message()-loop.

If you lock the mutex before `read_message()` loop and unlock afterwards, then for sure it will be locked "forever" ;) If you only lock the mutex for `read_message()`, then the mutex will be unlocked for a certain time after reading which will allow another thread to acquire the mutex and send a message.

But if you want to do it in a really performant and scalable way, I may suggest you to take a look at our tokio (async) version of this library which provides the example of chat (it seems to be exactly the thing you tries to implement) out-of-the-box: https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs (the proper usage an extension of this example would require some knowledge and understanding of tokio though, but if you want to continue backend development in Rust and have some long-term projects, investing a bit of time into understanding of Rust and Tokio will definitely pay off).

Hope that helps.

**Comment by the-bass** [comment]
> If you only lock the mutex for read_message(), then the mutex will be unlocked for a certain time after reading which will allow another thread to acquire the mutex and send a message.

That did the trick, indeed! However, I will follow your suggestion and use the Tokio version instead. Thanks a lot for taking the time, it's highly appreciated!
