### ISSUE TITLE
Suggestion: use a better data structure for InputBuffer

### ISSUE THREAD

**Issue by bluetech** [snapview/tungstenite-rs#8]
`InputBuffer` currently uses a growable `Vec`. It appends new data, and drains old data.

The `drain` part incurs a `memmove` of the `Vec`s content. Since memory copies take up the majority of the runtime, I think the library should try to avoid them when possible. In this case the library can use another data structure for that. The usual one would be a growable ring buffer, this way the `drain` would not incur a copy, only growing/shrinking the buffer would.

Luckily, the standard library already has an implementation of a growable ring buffer, [`VecDeque`](https://doc.rust-lang.org/std/collections/vec_deque/struct.VecDeque.html). So I think it'd be worthwhile to try it and see if my theory is true :)

One thing we need to be able to do is to read directly into the buffer, again to avoid copies. For `Vec` it's implemented with the help of `bytes::BufMut::bytes_mut`. But `BufMut` is not implemented for `VecDeque`. I opened https://github.com/carllerche/bytes/issues/94 - maybe it's possible.

[Side note: the implementation of `InputBuffer::read_from` is in fact not technically safe, because it is actually illegal in Rust to do `Read::read` into an uninitialized buffer. That's because a `Read` implementation is technically free to read the buffer that's passed into it, and reading uninitialized bytes is illegal in Rust. I'm not sure how much I care about that, though - a `Read` implementation which does something like that would be pretty odd.]

**Comment by agalakhov** [comment]
The limitation of Read is, we need a single block of memory to read into. Using a ring buffer results in splitting the free space in two parts. I don't think we can use readv here.

My opinion is, instead of optimizing memmove here it were nice to optimize the data consumer to parse all data available. In this case memmove will be called only for a small amount of data and can be neglected. This also probably will fix the UTF-8 issue in Autobahn tests.

**Comment by bluetech** [comment]
Right, the memory won't be contiguous anymore, though I do think `readv` is perfectly usable in this context. Whether it'd be more performant overall than the `memmove`, I'm not sure; but would be fun to try.

But I think you are right, if we only ever drain the entire buffer, then a memmove is not needed, and a simple `Vec` is definitely better. So that would negate this issue.

**Comment by bluetech** [comment]
Oh, about `readv`, I see what you mean. The `Read` trait does not expose the option, unfortunately...

**Comment by agalakhov** [comment]
Yes, and the Read stream is not always a TCP stream. It may be also TLS or some other high-level wrapper.

I believe the situation that a complete packet is immediately followed by incomplete one within the same read() is very rare. Thus memmove is not expected to be called at all. Did you see the opposite on the profiler?

**Comment by bluetech** [comment]
I imagine they way std could add readv support is by adding a function to `Read` with a default implementation which only uses `read`, and that supporting implementers could override. But a TLS socket would not have readv most likely, right.

And you are correct, after the fix [here](https://github.com/snapview/tungstenite-rs/pull/7/commits/8e49bea00fea274cd48a17cb848000186e5ee7e9), this is the memmove breakdown I see (the percentages are out of the entire runtime, memmove takes 53% total. Ignore the `String::clone`, that's from my own code):

```
+ 16.93% <tungstenite::protocol::WebSocket<Stream>>::write_pending 
+ 12.03% <collections::string::String as core::clone::Clone>::clone
+ 11.51% tungstenite::protocol::frame::frame::Frame::parse         
+ 7.83% tungstenite::protocol::message::IncompleteMessage::extend  
+ 4.62% tungstenite::input_buffer::InputBuffer::reserve            
```

I haven't checked exactly where the `memmove` in `InputBuffer::reserve` comes from (the `drain` or the `reserve`) but it's anyway much less significant than before.

**Comment by application-developer-DA** [comment]
The `InputBuffer` has been replaced by a different implementation: https://github.com/snapview/tungstenite-rs/pull/214

So I think this particular issue one could be closed 🙂
