### ISSUE TITLE
Is there way to use http and websocket for example?

### ISSUE THREAD

**Issue by Lightnet** [snapview/tungstenite-rs#80]
I just new on rust but not sure how to get http with websocket. Since I wanted to have minimal to host simple web browser page using websocket. I hope have time to create simple example since there no example on http just using TcpStream from just rust very simple rust http hello world.

**Comment by application-developer-DA** [comment]
Yes. But it's not part of the `tungstenite-rs` as `tungstenite-rs` only handles the websocket part. You can use [warp framework](https://github.com/seanmonstar/warp) if you want to combine HTTP and WS on a server side.
