### ISSUE TITLE
How to deal with Error::Capacity on reads?

### ISSUE THREAD

**Issue by najamelan** [snapview/tungstenite-rs#82]
On reading this error can be returned by: https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/frame/mod.rs#L165

I wonder how to interpret this. It seems the buffer is created with limit `usize::max_value()`, which must be huge. When can this happen? What to do when it does? 
Is the socket still operational?
Should we try to send a close frame, or just consider it's sudden death?
Is there a way to trigger this error to test it?

I had a hard time digging through `InputBuffer` trying to figure this out.

**Comment by agalakhov** [comment]
This error means you're receiving more messages than you're able to handle. Either the peer tries to flood you with messages (DoS attack?) or your code handles incoming messages way too slow (a bug?).

By default this never happens since the buffer is unlimited. However one could set smaller limit that `usize::max_value()`.

**Comment by najamelan** [comment]
Thanks for clarifying. As I'm preparing the 0.1 release of ws_stream_tungstenite I was going through the TODO items and came back to look at this. I try to understand:

> However one could set smaller limit that usize::max_value().

The relevant code doesn't seem configurable:
```rust
            let size = self
                .in_buffer
                .prepare_reserve(MIN_READ)
                .with_limit(usize::max_value())
                .map_err(|_| Error::Capacity("Incoming TCP buffer is full".into()))?
                .read_from(stream)?;
```

So how could one set a smaller limit?

**Comment by application-developer-DA** [comment]
I think you're right, the corresponding code which would allow this value to be configurable is missing.

**Comment by najamelan** [comment]
Ok, so I'm going to suppose this never happens on reads.
