### ISSUE TITLE
Possible error in FrameCodec::write_pending

### ISSUE THREAD

**Issue by najamelan** [snapview/tungstenite-rs#83]
This method has a loop as:

```rust
while !self.out_buffer.is_empty() {
    let len = stream.write(&self.out_buffer)?;
    self.out_buffer.drain(0..len);
}
```

However the documentation of `std::io::Write::write` states:

> If the return value is Ok(n) then it must be guaranteed that n <= buf.len(). A return value of 0 typically means that the underlying object is no longer able to accept bytes and will likely not be able to in the future as well, or that the buffer provided is empty.

If anything ever returns `Ok(0)` here, this hangs in an infinite loop. I think `0` len is sometimes returned to signal an unexpected EOF. I think this loop should check for that and probably bubble up an error instead of looping infinitely.

**Comment by agalakhov** [comment]
This is a bug. It seems to be harmless since things like `TcpStream` never actually return `Ok(0)` on write. Their indicator of "connection closed" is `io::Error` with `ConnectionReset` kind. Corrected this anyway.

**Comment by najamelan** [comment]
Thanks or the quick resolution. The fix looks good. The thing is that tungstenite works on any `io::Read/Write`, not just `TcpStream`. I don't intend to use it other than to communicate to browsers, but sometimes people do. Also testing code might not use `TcpStream` but a mock network stream.
