### ISSUE TITLE
WebSocket::write_pending may lose pongs and messages

### ISSUE THREAD

**Issue by nox** [snapview/tungstenite-rs#9]
```rust
        if let Some(pong) = replace(&mut self.pong, None) {
            self.send_one_frame(pong)?;
        }
        // If we have any unsent frames, send them.
        while let Some(data) = self.send_queue.pop_front() {
            self.send_one_frame(data)?;
        }
```

If `self.send_one_frame(pong)` or `self.send_one_frame(data)` return `Err(_)`, `self.pong` or the frame that was popped off from the front of `self.send_queue` will be lost and never sent.

**Comment by application-developer-DA** [comment]
You won't believe, but that was also my feeling when I first read this piece of code before we published the library :) However @agalakhov showed me that actually the messages aren't lost, take a look at `FrameSocket::write_frame()` (it is called by `send_one_frame()`), the messages are written to the `out_buffer` and only then the actual sending is performed by `FrameSocket::write_pending()`.

**Comment by nox** [comment]
Oh, neat.

**Comment by agalakhov** [comment]
Thank you, probably this piece of code needs an additional comment since it looks confusing.
In fact, all send_*() functions are guaranteed to buffer the given information regardless of their error state (unless the error is so fatal that we can't continue at all and close the connection anyway).
