### ISSUE TITLE
How to access the internal buffer

### ISSUE THREAD

**Issue by ppamorim** [snapview/tungstenite-rs#90]
Hi, I am trying to find ways to access the internal buffer of a message instead of using `Message.into_data()` since it returns a `Vec<u8>`. I am not sure how tungstenite really works but I suspect it allocates the data on a internal buffer in the stack. When using `Vec<u8>` it moves the data to the heap and creates a unecessary overhead (I think). My Application is using only stack buffers so I would like to do the same with tungstenite. 

TLTR: Any idea of what I can do to access this internal buffer in the stack?

Thanks.

**Comment by najamelan** [comment]
Tungstenite stores binary, ping and pong messages as an enum variant with a `Vec<u8>`. So when calling `Message.into_data()` on those you will just destructure (note the method takes self by value, not by reference) the enum and get the already existing Vector without copying. 

I don't think there is a way to construct `tungstenite::Message` entirely on the stack.

**Comment by ppamorim** [comment]
That's ok. Thank you!
