### ISSUE TITLE
Base HTTP-types (request, headers, response, status code, etc) on the ones from the http crate

### ISSUE THREAD

**Issue by sdroege** [snapview/tungstenite-rs#92]
Currently tungstenite defines its own types for all of this but internally uses the http crate already. It seems like it would make sense to re-use the types from the http crate instead as that would also allow easier integration with other code.

Doing this might also simplify e.g. https://github.com/snapview/tungstenite-rs/issues/70 and could for example also allow the HTTP part of the WebSocket connection to be handled by another HTTP library with tungstenite only taking care of populating the request, parsing the response and then taking over the upgraded HTTP connection.

**Comment by agalakhov** [comment]
Yes, this has to be done. The only reason for having own types is, the `http` crate did not exist at the time of Tungstenite creation. Now Tungstenite depends on `http` too and implements conversion between `http` types and own types in some cases. The plan was to switch to `http` completely but this did not happen yet.

**Comment by sdroege** [comment]
Would you accept a PR doing that against master? Not saying that I'll be doing it anytime soon, but I can put it on my list (but if anybody reads this before there's a PR, please feel free to go ahead).

**Comment by agalakhov** [comment]
Yes, please! It would be a breaking change, so it requires corresponding version increment.

**Comment by sdroege** [comment]
I started looking into this but it will probably take a while :) I've moved the headers over, not very beautiful yet but I'm going to clean that up once all the pieces are in place.

As part of this I'd also change a bit how serialization of all these types happens instead of having a big static `write!` block, for example.
